def ascii_sign(index):
    signs = ["""MMMMWWMMMMMMMWXOdc;;;:xNMMWNk;';clc:;;,,,,,,,,,;;;:clod0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMWWMMMMMMMMMMWKko:;lOKOdc,'.'',,,,;;;;;;;;;;;;,,,,,'cO0000KNWMMMMMMMWNXXNNWMMMMMMMMMMMMM
MMMWXXWMMMMMMMMMMWWXx:,,,''',;;;;;;::::::::::::::::::;;;;;,,,,:oOXWWMWXOxk0KNWWMMMMMMMMMMMM
MMMMWNWMMMMMMMMMWN0x:'.',,;;;;:::::::::::::::::::::::::::::;;,,'';oOXKO0KNWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWNOl,'',;;;:::::::::::::::::::::::::::::::::::::;;;,'':d0NWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWNkc,',;;;;::::::::::cccccccccccccccccccccc:::::::::::;,'':xXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMWNOc'',;;;;::::::::ccccccccccccccccccccccccccccccc::::::::;;'':kXWMWWN0KWMMMMMMMM
MMMMMMMMMW0l,',;;;::::::::cccccccccccccc:::ccclllccccccccccccc::::::::;,''cOXKxlcOWMMMMMMMM
MMMMMMMWNx;'';;;:::::::cccccccccllc:;;clcccllc:::,,;::;;:cccccccc:::::::;,',:cokKWMMMMMMMMM
MMMMMMWXo'.,;;::::::::cccccccllc:;;',o0KKKKK0Okdl:;:lxkl;;ccccccccc::::::;;'.:OWWMMMMMMMMMM
MMMMMWKl'',;;:::::::ccccccclc:;;:locd0KKKKKKKKXKKK0kodOKOc;:llccccccc::::::;,':0WMMMMMMMMMM
MMMMWKl.';;;::::::cccccclllc;;lkOkxOKKKKKKKKKKKKKKKKK00KKx;;llllccccccc:::::;,.:ONMMMMMMMMM
MMMMNd,',;;::::::;,,,;;,;:;';k0kdxOKXKKKKKKKKKKKKKKK00OOkc':lllllccccccc:::::;'.,xWMMMMMMMM
MMMWO;.,;;;;,,,,;;;;:cc;;cc:xOdoOKKKKKKKKKKKKOdodddxdoodoc;,;cllllccccccc:::::;'.dNMMMMMMMM
MMMWd',;:ccccloxdc:coxO0KKOk0OcdKKKKKKKKKKKKKK0OO0000KKKKK0o,;llllllcccccc:::::,.;OWMMMMMMM
MMMNdckOOO0O000klckKKKKKKK00K0xlkKKKKKKKKKKKKKKKKKKKKKKKKKKx::lllllllccccc:::::;'.lK00NMMMM
MMMWxd00000000OockKKKKKKKKKKKK0xdOKKKKKKKKKK0O000000OOkkkxo:;loollllllccccc::::;,'';;oNMMMM
MMMWOk00000000xlxKKKKKKKKKKKKOxO0KKKKKKKKKK0doxxxxxxxxdol,.;oooollllllcccccc::::;'.cOXWMMMM
MMMW0O0000000koo0KKKKKKKKKKXOdxKKKKKKKKKKKKK00KKKKKKKKKKKd,:ooooollllllccccc:::::,.oNWMMMMM
MMMWKO0000000xlxKKKKKKKKKKKXOlxKKKKKKKKKKKKKKKKKKKKKKKKK0c,loooooolllllcccccc::::,.lXWMMMMM
MMMWKO0000000dckXKKKKKKKKKKXOco0KKKKKKKKKKKKK000000OOkkd:':odooooolllllccccc::::;,.cdONMMMM
MMMWKO0000000o:kXKKKKKKKKK000xllok0KKKKKKKKKkodxxkkkxxdo;':ooooooolllllccccc::::;,.,ckNMMMM
MMMW0k0000000d:xKKKKKKKKKKOxOKKOxllxKKKKKKKKK0KKKKKKKKKKk:;odooolllllllccccc::::;''oXWMMMMM
MMMWkx0000000kcckKKKKKKKKKKkox0KKKxlOXKKKKKKKKKKKKKKKKXKx;:oooooolllllccccc:::::;',dO0NMMMM
MMMNxo00000000x;,lxkO0KKKK0Oo:o0KKklxKKKKKKKKKKKKK0Okxol;:looooolllllcccccc:::::,.'::dNMMMM
MMMWd:k0000000Od,':cccllol:;;..;lodo:lxkkkkkkkxo:::::::cloooooollllllccccc:::::;''o0KNMMMMM
MMMWd',:lxO0000Odc::c:;;;'.,;::;;,,lxoloodddxkOkc';odddooooooollllllcccccc::::;,.cKWWMMMMMM
MMMM0:...';cloxkkkdllc:;,,:loooool;,lkKKKKKKKKKXOc,coooooooolllllllccccc:::::;,.;kNWXXWMMMM
MMMMNk,.,;,'',,;;;;;:;,,:clllloooooc,,lkKKKKKKKKKO:;looooolllllllccccccc:::::,',okxolxNMMMM
MMMMMNx,.,;;:::::;;::cccclllllllllool:,,lOKKKKKKKKo,coolllllllllcccccc::::::,'';clokKWMMMMM
MMMMMMNk;.,;;:::::::cccccccclllllllllol:':kKKKKKKKo,:lllllllllccccccc:::::;,';x0KXWWMMMMMMM
MMMMMMMW0c'',;;::::::cccccccccllllllllllc,c0XKKKK0l,:llllllcccccccc::::::;'':ONMMMMMMMMMMMM
MMMMMMMMWXd,'';;:::::::ccccccccccllllllll;,dKKKKKk;,cllccccccccc:::::::;,'',l0NWMMMMMMMMMMM
MMMMMMMMMMN0l,',;;;:::::::cccccccccccccclc,:OKKKkc,:cccccccccc:::::::;,''ckkoclxKNWMMMMMWWM
MMMMMMMMMMMWNOl,',;;:::::::::ccccccccccccc;';loc,,:cccccccc::::::::;,',ckXWWWXkoclxKNWMN00N
MMMMMMMMMMMMWWN0o,'',;;:::::::::::ccccccccc:,,,,;:cccc::::::::::;;,,;lONWMMMMMWWXkoclkKKo;d
MMMMMMMMMMMMMMMMWKxc,'',;;;;:::::::::::::::::::::::::::::::::;;,'':xKWMMMMMMMMMMMMWKklcc,..
MMMMMMMMMMMMMMMMMMWN0d:,'',,;;;:::::::::::::::::::::::::;;,,'',:okXWMMMMMMMMMMMMMMWN0d;....
MMMMMMMMMMMMMMMMMMMMMWNKko:,''',,;;;;;;;;::::::::;;;;,,''';:lx0XWWMMMMMMMMMMMMMMMMWKkoc:;,'
MMMMMMMMMMMMMMMMMMMMMMMMMWNKOdoc:;,''''',,,,,,,''',,;:coxOKNWWWMMMMMMMMMMMMMMMMMMMMMWWWNXK0
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0OOkxddoooooodxkO0KXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWNXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW""", """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXKx::xOOOkoccoxO0KXNNNKOkO0XNNWN0dlcclloKMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxdollccccccccccccccccclloodk0XNWMWXkolodkO0XWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0kdlcccclloooooooooooooooooolc,.';:ldk00kxk0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWWKkdlccclooooooooooooooooooooool:,....'.':llclkXWMMMMWXXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWXOdccclooooooooooooooooooooolc;,'',:coxkOx::dkxolox0NWXkoOMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWXkoccloooooooooooooooooooool:,..';ok0KKKKKKKOc:x0OkdlldkkkOXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWXklccloooooooooooooooooooolc,'',:dOKKKKKKKKKXKKO::x000OxocoONWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWNOocclooooooooooooooooooooc;',:ok0KKKKKKKKKKKKXKKKk:lO0000Oxoco0XNWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWKdccloooooooooooooooooool:,,:oOKKKKKKKKKKKKKKKKKKKK0o:oO00000OxlcdKNWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWNkl:loooooooooooooooooolc;';lkKKKKKKKKKKKKKKKKKKKKKKKKOc:x0000000Odco0NMMWWWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWXxccloooooooooooooooooo:'.:d0KKKKKKKKKKKKKKKKKKKKKKKKKKKd:oO0000000OxclkXXOdOWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWKd:cooooooooooooooooooc,':x0KKKKKKKKKKKKKKKKKKKKKKKKKKXK0x::k000000000xlcxOkxKMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWKd:coooooooooooooooool:,ckKKKKKKKKKKKKKKKKKKKKKKKKKKK0xol:,..d00000000Odc;ckNWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWXx:cooooooooooooooool:,cx0KKKKKKKKKKKKKKKKKKKKKKKKKKKKd..'''..o00000Oxlcccc:cONMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNOccooooooooooooooool,,o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKK0l..'::,:x000Ox:,;loool:lKWMMMMMMMMMMMMMMMMM
MMMMMMMMMWKo:loooooooooooooool'.o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0c.'..:dkkkdc:;;cooooooc:xNMMMMMMMMMMMMMMMMM
MMMMMMMMMNkccoooooooooooooool'.;OXKxd0KKKKKKKKKKKKKKKKKKKKKKKKKX0c.':;.',,,,;coooooooool:cOWMMMMMMMMMMMMMMMM
MMMMMMMMMXd:loooooooooooooooc..c0KKdo0KKKKkdOKKKKKKKKKKKKKKKKKKKKx'.,llcccloooooooooooooc:kWMMMMMMMMMMMMMMMM
MMMMMMMMWKl:loooooooooooooooc..d00KkdOKKKKOxOKKKKKKKKKKKKKKKKKKKKKo..:oooooooooooooooooolckWMMMMMMMMMMMMMMMM
MMMMMMMMW0c:ooooooooooooooool'.oxlxxlkKKKK0odKKKKKKKKKKKOO0KKXKKKKKo..coooooooooooooooool:xWMMMMMMMMMMMMMMMM
MMMMMMMMWOccooooooooooooooooo;.,l;lxdkKKKX0:;kKKKKKKKKK0l,lOKKKKKKXO:.:oooooooooooooooool:xWMMMMMMMMMMMMMMMM
MMMMMMMMW0l:oooooooooooooooooc..',:ooxKKKX0o:xKKKKKKKKKKl.;kKKKKKKK0c'coooooooooooooooool:xWMMMMMMMMMMMMMMMM
MMMMMMMMW0l:ooooooooooooooooooc'....;xKKKKKxcdKKKKKKKKKKl,xKKKKKKK0l';ooooooooooooooooool:kWMMMMMMMMMMMMMMMM
MMMMMMMMWKl:looooooooooooooooool:;..,OXKKKXOcoKKKKKKKKKOc:OXKKKKKx;.'loooooooooooooooooolckWMMMMMMMMMMMMMMMM
MMMMMMMMMXx:coooooooooooooooooooooc.;OXKKKXOcl0KKKKKKKKkcdKXKK0x:'':loooooooooooooooooooccOWMMMMMMMMMMMMMMMM
MMMMMMMMMWOc:oooooooooooooooooooooc'c0XKKKK0olOKKKKKKKKd;cooc:;,;clooooooooooooooooooool::OWMMMMMMMMMMMMMMMM
MMMMMMMMMWXd:looooooooooooooooooooc,c0KKKKX0ockKKKKKKK0c..,,;:cloooooooooooooooooooooooc:xXWMMMMMMMMMMMMMMMM
MMMMMMMMMMWOc:loooooooooooooooooooc,c0XKKKKKo:xKKKKKKK0c.,loooooooooooooooooooooooooooc:oKWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNxccooooooooooooooooooo:'lKXKKKKO;.dKKKKKKKO;.:oooooooooooooooooooooooooool:lONWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWXd:coooooooooooooooooo;'dKKKKK0c..oKKKKKKKx''looooooooooooooooooooooooool:;ldxKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWXd:cloooooooooooooooc';OKKKKKd.  c0KKKKKKo';ooooooooooooooooooooooooool:cxkO0XMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWXkc:loooooooooooooo:.c0KKKKk,  .c0KKKKKk;'coooooooooooooooooooooooooc:lONWWWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWNOl:cloooooooooool,'dKKKK0c....c0KKKK0l':oooooooooooooooooooooooolc;:oxxxxkKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWXxc:looooooooooc.'dKKKOc..:;.c0KKKKk;'loooooooooooooooooooooooc:lxOOOOOOOXWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMN0dcclooooooool,.,cl:,';lo:.;OKKKk:':oooooooooooooooooooooolccxKWWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWNOdccloooooool:;,,;:loool,'o0ko;,:oooooooooooooooooooolc:cdOXNNNNNXXNNWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWNKxlcclooooooooooooooooc'.''';loooooooooooooooooollc:::loodddddddddd0WMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXOdlclloooooooooooooolc:clooooooooooooooooolccclxO00KKKXXXXXXXXXXNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWWXOdolcclooooooooooooooooooooooooooollccc::lOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0kdolccccllllooooooooooolllcccccodxO0xokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0kxddolllllllllllllloodxk0KNWWMWNkokXWMMMMMMMMMMMMMWKNMMMMMMMMMMMMMMMMM
WNNWWMMWWNNWWWMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXKKKKKKKKKXNNWWWMMMMMMMMWNOoxKWMMMMMMMMMMMMXdkWMMMMMMMMMMMMMMMM
""", """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOkxdoollcclcccccclloddoco0XNWWWXKOkxdddddxO0KKXNNWNNWMWXxco0WMWWXOl:lxk
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kdlccclllooooooooooooooolllcccloxkkOOOOOOkkkxkOKNWWNKOkXWMWWXkccdkkkkkkdl:d
MMMMMMMMMMMMMMMMMMMMMMMMWWX0xolccloodddddddddddddddddddddddddoollccodOKNWNNNXXXXXXOxoldO0Okkxxxl:ckKNWWWKdc
MMMMMMMMMMMMMMMMMMMMMMWXOdlccloddddddddxxxxxxxxxxxxxxxxxxxxxxdddddolccld0XWWWNKOxolcccldkO0KKNWNKKXWMMMMMNK
MMMMMMMMMMMMMMMMMMMWNKxlccloddddddxxxxxxxxxxkkkkkkkkxxxxxxxxxxxxxddddollclxOOkdooooollloxx0MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWWKdccloddddddxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxddddolccoOKXXXXX0klc::OMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWKxlcloddddxxxxxxkkkkkkkkkkOkxooodddoddxxxxxxxxxxxxxxxxddddlclkXWN0kolcc:cOWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWNOlclodddddxxxxkkkkkkOOOOkkxdddddoooodddxxdddddolclooooddddddolco0KK0000000XMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWKdccoddddxxxxxkkkkkOkkxddddxxxxxkOOO000OkxxxxxxxddxxdddoooocldddoclxXWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMNOlcloddddxxxxkkkkkxdooodddxxxxxk0KKKKKKKKKXXKKK0Okxkkkkkkkkkd:lxddolcdKWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWNkccodddddxxxxkkkkddxxxooxkkkO00KKKKKKKKKKKKKKKKKKKKXKK00OOkxl::oxxdddlco0WWNK0XMMMMMMMMMMMMMMMM
MMMMMMMMMWNkccoddddxxxxkkkkkolk0OkO00KKKKKKKKKKKKKOxk0KKKKKKKKKKKKKKKKKkc,;oxxxdddoclk0OkkKMMMMMMMMMMMMMMMM
MMMMMMMMMWOccoddddxxxxkkkkOkcl00OKKKKKKKKKKKKOkxxdoc::loddddxddxxxddkkddoc:dkxxxdddlco0WWWWMMMMMMMMMMMMMMMM
MMMMMMMMWKo:lddddxxxxkkkOOOkld0O0KKKKKKKKKKK0x:;:;;::ldxkOOOOOOOOkxlcclc;;okkkxxxdddl:dXNXNMMMMMMMMMMMMMMMM
MMMMMMMMNxclodddxxxxkkkOOOOkld000KKKKKKKKK0OOxoodxkO0KKKKKKKKKKKKXK0l',loxkkkkxxxxddoccxkxKMMMMMMMMMMMMMMMM
MMMMMMMW0lcoodddxxxkkkkOOO0OdxKKKKKKKKKKKKK000KKKKKKKKKKKKXXKK00OkxdlcxO0OOOkkkxxxxddl:o0NWMMMMMMMMMMMMMMMM
MMMMMMMNx:lodddxxxxkkkOOO00koxKKKKXKKKKKKKKKKKKKKKKKKKKKOxxxdxxxxddxxk000OOOOkkkxxxxdocckWMMMMMMMMMMMMMMMMM
MMMMMMWXdclddddxxxkkkkOOO00xokKKKKKKKKKKKKKKKKKKKKKKKOkxxkkOO0KKKKKKK0000OOOOkkkxxxxddl:dNMMMMMMMMMMMMMMMMM
MMMMMMW0lcoddddxxxkkkOOOO00doOKKKKKKKKKKKKKKKKKKKXKOkk0XNNXXXXXXKKKKK00000OOOkkkxxxxddl:oOXMMMMMMMMMMMMMMMM
MMMMMMW0lcooddxxxxkkkOOOO00doOKKKKKKKKKKKKKKKKKKK0kkKNNNNNNXXXXXKKKKK00000OOOkkkxxxxddoclkXMMMMMMMMMMMMMMMM
MMMMMMW0ccodddxxxxkkkOOOO0Ooo0KKKKKKKKKKKKKKKKKKkokXWWNNNNNXXXXXXKKKK00000OOOkkkxxxxddocoKWMMMMMMMMMMMMMMMM
MMMMMMW0lcodddxxxxkkkkOOO0Ooo0KKKKKKKKKKKKKKKKK0loXWWNNNNNXXXXXXKKKKK00000OOOkkkxxxxddlcoKWMMMMMMMMMMMMMMMM
MMMMMMWKoclddddxxxkkkkOOO0OodKKKKKKKKKKKKKKKKKK0odXNNNNNNNXXXXXXKKKK00000OOOOkkkxxxxddl:dXWMMMMMMMMMMMMMMMM
MMMMMMMNx:loddddxxxkkkkOO0Ooo0KKKKKKKKKKKKKKKKKKkd0NNNNNXXXXXXXKKKKK00000OOOkkkkxxxdddc:lxKMMMMMMMMMMMMMMMM
MMMMMMMWOccoodddxxxkkkkOOOOooKXKKKKKKKKKKKKKKKKKOdOXNNXXXXXXXKKKKKK00000OOOOkkkxxxxddocldxKMMMMMMMMMMMMMMMM
MMMMMMMWKoclodddxxxxkkkkOOOoo0KKKKKKKKKKKKKKKKKK0xOXXXXXXXXKKKKKKK00000OOOOkkkkxxxdddlcxNWMMMMMMMMMMMMMMMMM
MMMMMMMMWOccoddddxxxxkkkkOOxoxKKKKKKKKKKKKKKKKKKkokXXXXXKKKKKKKK000000OOOOkkkkxxxdddl:oKWMMMMMMMMMMMMMMMMMM
MMMMMMMMWNxcloddddxxxxkkkkOkolOKKKKKKKKKKKKKKKKKkcl0KKKKKKKKKK0000000OOOOkkkkxxxxddoc:d0XNWMMMMMMMMMMMMMMMM
MMMMMMMMMWXdcloddddxxxxkkkkkxllkKKKKKKKKKKKKKKKK0xod0K0000K00000000OOOOOkkkkxxxxddoccooooo0MMMMMMMMMMMMMMMM
MMMMMMMMMMWXdcloodddxxxxkkkkOkolx0KKKKKKKKKKKKKKKK0xlc::ldO000000OOOOOkkkkxxxxdddocckNNNX0XMMMMMMMMMMMMMMMM
MMMMMMMMMMMWXxccodddddxxxxkkkkkdld0KKKKKKKKKKKKKKKX0o',ldookO0OOOOOOkkkkkxxxxdddoclONWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWNklclodddddxxxxkkkkxookKKKKKKKKKKKKK0kdodkO0OxodkOOOkkkkkkxxxxxddol::d0XWWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWWKdccooddddxxxxxkkkxolx0KKKKKKKKKOdooxO000000kllxkkkkkxxxxxddddlccoddoloxk0XWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWNOocloodddddxxxxxkxdloOKKKKK0koodkO000000000kl:oxxxxxxxddddocco0NWWNKOkdoo0MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWXOocloodddddxxxxxxo::xKK0kxdxO0000000000000Oo:lxxxxddddoc:lkXWMMMMMMMWNXNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWNOdlclooddddxxdol:;:lxxxk00000000000000000Od:cddddolcclllodkOKNWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMN0xlcclooddoclollodkO00000000000000000000Od::llcclx0XXK0kdoooodk0XNWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXOdlccllc:lxkOO0000000000000000000000OOxl:colcldk0XNWMWWXKOkdolodKMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWWX0kdlc:,;lkOOOO00000000000OOOkkxdooooxOKNNX0kdoooxOKNWMMMWNX0dOWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0Oxdlodddooddddddddooooooolc::okKNWMMMMMWNXOxdoodkKNWWXkd0MMMMMMMMMMMMMMMM""", """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMWNOx0KOk0NWMMMMMMWWX0xdx
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOkxdoooollloooolloooodxOKXNWMMMMMMMMMMMMMN0xdxxk0XNWMMMMMMMMMWKkd
MMMMMMMMMMMMMMMMMMMMMMMMMMWX0xoc:::cllooodddddddddddolc:::clodkKXWMMMMMMMWKkddddxk0XNWMMMMMMMMMWKk
MMMMMMMMMMMMMMMMMMMMMMWNKko:::codxxxxxxxxxxxxxxxxxxxxxxxxdoolc::cokKNMMMWXkddxk0KXNWMMMMMMMMMMMMN0
MMMMMMMMMMMMMMMMMMMMWKxl::cldxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdoc::lkKNXkxk0XNWWMMMMMMMMMMMMMMMWN
MMMMMMMMMMMMMMMMMWNOo::codxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoc::ldkKNWMMMMMMMMMMMMMMMMMMMMW
MMMMMMMMMMMMMMMWNkl::ldxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl:;cONMMMMMMMMMMMWWNNWMMMMMM
MMMMMMMMMMMMMWNOl;:oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl::d0XXXXXXKK0Okxx0NMMMMMM
MMMMMMMMMMMMW0o;:oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo:';ldxdoolllcclkNMMMMMMM
MMMMMMMMMMMNx:;ldxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl:,;cl:lOK0kdolcclOWMMMMMMM
MMMMMMMMMWKo;:oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxol:cloodxO0Od:l0WWNKOxoo0WMMMMMMM
MMMMMMMMWKl;cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd:',:okO000000Od:cONNNXX0k0WMMMMMMM
MMMMMMMW0c,cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl..,'';lk000000Oxc:oxxdoolxNMMMMMMM
MMMMMMMKl,cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdoc;.':loc;;lk00000Okc;o0X0OdkNMMMMMMM
MMMMMMNd;:dxxxxxxxxxddoolllllllloddxxxxxxxxxxxxolllllllllc:;,':ok0KKKK0l,:k000000x:;kWMMWWWMMMMMMM
MMMMMWO:;oxxxxxxxxl;,:llllllllllc:;;;cloddxxxl:cokO0000OOOkxxk0KXKKKKKKKo'cO00000Oo;cKWNNNWMMMMMMM
MMMMMXo;cxxxxxxxxc';dOKKKKKKKKKKK0Okdoollc::,,lOKKKKKKKKKKKKKKKKKKKKKKKKO:,d000000kc;xK0O0NMMMMMMM
MMMMM0:;oxxxxxxxd;'dKKKKKKKKKKKKKKKKKKKKK0d,'oKKKKKKKKKKKKKKKKKKKKKKKKKKKo'cO00000Od;lKWNNWMMMMMMM
MMMMWk;:dxxxxxxxxc':kKKKKKKKKKKKKKKKKKKKKXO::OKKKKKKKKKKKKKKKKX0dx0KKKKKKx,:O000000k::0WMMMMMMMMMM
MMMMXo;lxxxxxxxxxxl,,:ok0KKKXKKXKKKKKKKKKK0l;dKKKKKKKKKKKkxOKKK0l:OXKKKKKO:;k000000Ol:xNMMMMMMMMMM
MMMMXl;lxxxxxxxxxxxdl:,,;:cloxkkO0KKKKKKKKKO::OKKKKKKKKKO:,xKKK0lcOXKKKKKO::k000000Ol:d0KXWMMMMMMM
MMMMXl;lxxxxxxxxxxxxxxxdolc:;;;;::ccccclodxko:o0KKKKKKKKx:o0KKKklxKKKKKKKk:cO000000Ol:dOdxNMMMMMMM
MMMMXo;lxxxxxxxxxxxxxxxxxxxxxxxdddoc,.';:cldxl:kKKKKKKK0dlOKK0xokKKKKKK0x:;dO000000kc:kWWWWMMMMMMM
MMMMNd;cxxxxxxxxxxxxxxxxxxxxxxxxdocclxOKKKKKKx;l0KKKKKOdokKKKK00KKKKKOdc,,lO0000Oxoc,;OWWWMMMMMMMM
MMMMWk;:dxxxxxxxxxxxxxxxxxxdolccldk0KKKKKKKKKO:,d00Oxc,'cOKKKKKK0dclc',oxkO00Oko:;::,:kOoxNMMMMMMM
MMMMMKc;oxxxxxxxxxxxxxxdoc::coxOKKKKKKKXKKK0kxc..;:clool::xKKKKKk;.,;';x00OOxl::cddc,lKXkkNMMMMMMM
MMMMMNx;cdxxxxxxxxxxdlc:coxO0KKKKKKKKKKK0xoloo:cdxk0KKKKk:lKKKKx:':dxl,;oolccldxxxo;;kWMMMMMMMMMMM
MMMMMWKc;lxxxxxxxxxl;:oOKXKKKKKKKKKKKKkocldO0OO0KKKKKKK0o,;dOOo;:oxxxxo;,;coxxxxxdc,lKWMMMMMMMMMMM
MMMMMMWk:;oxxxxxxxo,;kKKKKKKKKXKKK0kdc''d0KKKKKKKKKKK0xlcdo,':coxxxxxxxxxxxxxxxxxl,:ddodx0WMMMMMMM
MMMMMMMNx;:dxxxxxxd;,cxO0KKKKKOxoc::cc''xKKKKKKKKKOxdllx0Kk;;oxxxxxxxxxxxxxxxxxxl;:ON0d:.cXMMMMMMM
MMMMMMMMNx;:oxxxxxxdc;',,:cccc:;:codxxc,;oxxkkkxddodkOKKOd::dxxxxxxxxxxxxxxxxxdl;:OWMMWNOkNMMMMMMM
MMMMMMMMMNx:;oxxxxxxxxdolllllodxxxxxxxxoc;,..;loxO00Oxdlccldxxxxxxxxxxxxxxxxxdc,cOWMMMMMMWMMMMMMMM
MMMMMMMMMMWOc;cdxxxxxxxxxxxxxxxxxxxxxxxxxxd:',coddollclodxxxxxxxxxxxxxxxxxxxo:,;oKWMMMMMMMMMMMMMMM
MMMMMMMMMMMWKd:;lxxxxxxxxxxxxxxxxxxxxxxxxxxxdlllloodxxxxxxxxxxxxxxxxxxxxxxdc;:xOxodOXWMMMMMMMMMMMM
MMMMMMMMMMMMMN0l;:odxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl;;oKWMWXOddx0NWMMMMMMMMM
MMMMMMMMMMMMMMMNOl;:ldxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl;,:xNWMMMMMWKkddkKWMMMMMMM
MMMMMMMMMMMMMMMMMNOo:;cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl::odllxKNWMMMMMWN0xkNMMMMMMM
MMMMMMMMMMMMMMMMMMMN0dc;:loxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdoc::lkXWWXOkOXWMMMMMMMMWWWMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWXOdc::clddxxxxxxxxxxxxxxxxxxxxxxxxxxxxdol::;,:xXWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWN0xoc:;:cloddxxxxxxxxxxxxxxxxdool::::cdk0OoldKWMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk::llccc:::cccccccccc::::cc:;:xKNWMMWNOoxNMMMMMMMMMMMMMMMMMMMMMMMMMM
KWMMMMMMMMMMMMMMMMMMMMMMMMMMMNxckNNNXK0kd:,;ldxxxxdl::xKNXOdld0NMMMMMNNWMMMMMMMMMMMMMMMMMMMMMMMMMM
OWMMMMMMMMMMMMMMMMMMMMMMMMMMWOcdXMMMMMMMWKxllkXWMWWN0olxKWWN0dlo0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
OWNXKXNWMWNXXXNWMMMMMMMMMMMMXol0WMMMMMMMMMWKxllkXWMMMNOolxXWMWKdloOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""", """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXKKKKKK000KKKKKXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0OkkkkkkkkkkkkkkkkkkkkkkkO0KKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWNXKOkxxkkO0KKXXXXXXXXXXXXXXXKK00OkkkkkOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWNKOxxxkO0KXXXXOdlloxOXXXXKKKXXXXXXXXXXK0Okxxk0XWWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWNXOxxxO0KXXXXXKxc:clc:;;lkx:;::cd0XXXXXXXXXXXK0Oxxk0NWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWNKkxxOKXXXXXXXXXx,cOKKKK0x:'..lkd:';kXXXXXXXXXXXXXK0kxxOXWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWNKkxk0KXXXXXXXXXXKl,dKKKKKKKO; ;0KK0d';OXXXXXXXXXXXXXXXKOxx0XWMMMMMMMMMMMMMWNNW
MMMMMMMMMMMWNKkxk0KXXXXXX0xllllo;'dXKKKKKKKx':0KKKKo'lKNXXXXXXXXXXXXXXXKOxk0NWMMMMMMMMMWXOxKW
MMMMMMMMMMWXOxxOKXXXXXXXk;':odoc'.oKKKKKKKK0l;dKKKKO:;OXXXXXXXXXXXXXXXXXX0kxkKWWMMMMMWN0dllxO
MMMMMMMMMN0xxOKXXXXXXXXKl'l0KKXKx:;kKKKKKKKKk;:0XKK0o;xXXXXXXXXXXXXXXXXXXXKOxx0NMMMWN0xllccld
MMMMMMMWNOdx0XXXXXXXXXXKl,dKKKKKKk:cOKKKKKKK0c,xKKKKx;oKXXXXXXXXXXXXXXXXXXXXKkdOXNXOdllllllld
MMMMMMWXOdk0XXXXXXXXXXXXx;oKKKKKKKk:l0KKKKKKKd,lKXKXO::ONXXXXXXXXXXXXXXXXXXXXKkdxkxxxkO000KKK
MMMMMWNOdkKXXXXXXXXXXXXX0c:OKKKKKKKo;oKKKKKKKk;:OKKK0l;kNXXXXXXXXXXXXXXXXXXXXXKkdxKNWWMMMMMMM
MMMMMN0dkKXXXXXXXXXXXXXXXd;oKKKKKKXOc:kXKKKKX0l;xKKKKo,dXXXXXXXXXXXXXXXXXXXXXXXKkdOXNNWMMMMMM
MMMMWKxx0XXXXXXXXXXXXXXXX0lcOKKKKKKKd;oKKKKKXKx:oKXKKx;oKKKKXXXXXXXXXXXXXXXXXXXXKxxOkxxk0XNNW
MMMMNOdkKXXXXXXXXXXXXXXXXXx:dKKKKKKXO:;kXKKKKKk;lKXKXk,';:::lkKXXXXXXXXXXXXXXXXXXOxkK0dccclod
MMMWKxx0XXXXXXXXXXXXXXXXXXKo:xKKKKKKKo,oKKKKKKk;lKXKXk'.:dxdl:cxKXXXXXXXXXXXXXXXXKkd0NN0oc:::
MMMW0dkXXXXXXXXXXXXXXXXXXXXOccOKKKKKXk:cOXKKKKk;lKKKXk::kKKKKOl;oKXXXXXXXXXXXXXXXXOdkNWWXxc::
MMMNOdOXXXXXXXXXXXXXXXXXXXXXd;dKKKKKK0l:OXKKKKOoxKKKX0olx0KKKK0o;dXXXXXXXXXXXXXXXX0xxKWMMNOll
MMWXkx0XXXXXXXXXXXXXXXXXXXXX0lcOKKKKK0d;cllllk00KKKKKKdcxKKKKKK0cc0XXXXXXXXXXXXXXXKkxOXNWWWKO
MMWXkx0XXXXXXXXXXXXXXXXXXXXXXx;lkxdc::::clol,,xKKKKKXOclOKKXKKKKl;kXXXXXXXXXXXXXXXKkdO0OkO0KK
MMWXkx0XXXXXXXXXXXXXXXXXXXKko;.,::cldk0KKKXKo,oKKKKKKx:dKKKKKKKKo:kXXXXXXXXXXXXXXXKkx0NXOxddd
MMWNkx0XXXXXXXXXXXXXXXXXKxlcodkO0KKKKKKKKKX0l:xKKKKKKo,xXKKKKKK0lc0XXXXXXXXXXXXXXXKkxKWMWXOdd
MMMNOdOXXXXXXXXXXXXXXXXXd;lOKKKKKKKKKKKKKK0ocxKKKKKKKo,dKKKKKKKx:oKNXXXXXXXXXXXXXX0xx00KNWN0x
MMMW0xkKXXXXXXXXXXXXXXXO:l0KKKKKKKKKKKKKKxcckKKKKKKKKx;l0KKKKKOc:OXXXXXXXXXXXXXXXXOdk0xlcldkx
MMMWXkx0XXXXXXXXXXXXXXXkcdKXKKKKKKKKKK0x:,lOKKKKKKKKX0l;dKXK0d;;kXXXXXXXXXXXXXXXXKkx0NWKx:'''
MMMMW0dkKXXXXXXXXXXXXXXOcl0KKKKKKKKK0x:..;kKKKKKKKKKKKOl;cllc,.oKXXXXXXXXXXXXXXXXOdkXWMMWXd;.
MMMMWXkxOXXXXXXXXXXXXXXXxcdKXKKKKKKKKOxdoco0KKKKKKKKKKKKOkxkOl;kXXXXXXXXXXXXXXXX0xxKWMMMMWNOc
MMMMMWKxx0XXXXXXXXXXXXXXXxco0KKKKKKXKKKKKOoxKKKKKKKKKKKKKKKK0ll0NXXXXXXXXXXXXXXKkdodOKNWMMMWK
MMMMMMW0xx0XXXXXXXXXXXXXXXOcckKKKKKKKKKKKKxx0XKKKKKKKKKKKKKKkcdKXXXXXXXXXXXXXXKkdkk:..;lk0XNW
MMMMMMMW0xx0XXXXXXXXXXXXXXX0ocd0KKKKKKKKKKKKKKKKKKKKKKKKKKKKocOXXXXXXXXXXXXXX0kdkNWNx,   ..,:
MMMMMMMMWKxxOKXXXXXXXXXXXXXXXkllOKKKKKKKKKKKKKKKKKKKKKKKKKKx:oKXXXXXXXXXXXXX0xdddx0NWKl.    .
MMMMMMMMMWXkxk0XXXXXXXXXXXXXXX0lcxKKKKKKKKKKKKKKKKKKKKXKKKOcc0XXXXXXXXXXXXKOxx0XOc';lxkc.   .
MMMMMMMMMMWN0xxOKXXXXXXXXXXXXXXKdcoOKKKKKKKKKKKKKKKKKKKKKOccOXXXXXXXXXXXX0xxOXWWWXo'...'. .,,
MMMMMMMMMMMMWXkdxOKXXXXXXXXXXXXXXOl:ckKKKKKKKKKKKKKKKKKKx;;kXXXXXXXXXXX0kxkKWWMMMMNk,.    .:d
MMMMMMMMMMMMWXOxxxxOKXXXXXXXXXXXXXKc.:OKKKKKKKKKKKKKKKK0l.,d0XXXXXXXK0kxkKXXXWWMMMMWO,....,dX
MMMMMMMMMMWN0kOKNXOxxk0KXXXXXXXXXXXx,c0KKKKKKKKKKKKKKKKKo. ';lOXXXKOkxOKNWWKOO0XWMMMWO,'dkc,:
MMMMWXKNWNKOOKNWMMWNKkxxO0KXXXXX0dl;.c0XKKKKKKKKKKKK0Oxo:';dd:lOOkxxOXWWMMMWXkxxOKXWWWOxKWNOc
MMMWNOx0KOk0NWMMMMMMWWX0xdxkO0K0o;;'.ckOOOOOOkkxxddolllodxkkkooxO00k0NWMMMMMWXkdddxk0KXNWWNOd
MMMN0xdxxk0XNWMMMMMMMMMWKkdxkkkdool:::cccccllllllodxxkkxxdddxOKNWWWKO0NWMMMMMWKxddddxOKNNKxdO""", """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXK00OOOOOOOOOOO00KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0OkxdddddddddddddddddddddddxkO0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kxooodxkkkkOOOOOOOOOOOOOOOOkkkkxdoddkOXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdoodxkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxddxkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMN0xoodkkOOOOOOOOOOOOOOOOOOOOOkOOOOOOOOOOOOOOkxoc:ldkXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWXOdodkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdolllodkOxdoxKWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNOoodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxdoolllodkO000000kdlxXWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMW0dodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkdlc:clodxkO000000000000kdokXWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWXxldkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkd:,:ldxkOO00000000000000000kdd0WMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWOookkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOx;.;:::ccccccoxO0000000000000OxoxXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNkldkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkl'.;lxO000Oxdl::lxO000000000000kodKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNxlxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxolccok0KKKKKKKKKK0xc;lk000000000000OooKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNxlxOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxolcldk0KKKKKKKKKKKKKKK0x::dO00000000000OooKWMMMMMMMMMMMMMM
MMMMMMMMMMMMWOldkOOOOOOOOOOOOOOOOOOOOOOOOkxdlcloxOKKKKKKKKKKKKKKKKKKKKKk:,dO00000000000kldXMMMMMMMMMMMMMM
MMMMMMMMMMMM0odkOOOOOOOOOOOOOOOOOOOOOkxdlccldk0KKKKKKKKKKKKKKKKKKKKKKKKKx,;x0000000000Oxc:kNMMMMMMMMMMMMM
MMMMMMMMMMMNxoxOOOOOOOOOOOOOOOOOOkkdlc:coxOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKd,ck00000000Oocolo0MMMMMMMMMMMMW
MMMMMMMMMMM0ldOOOOOOOOOOOOOOOkkxoc::cdk0KKKKKKKKKKKKKKKKKKKKKKKKKKKK0kxOKO;'d0000000ko:okxlkNMMMMMMMWXKO0
MMMMMMMMMMWklxOkOOOOOkOOOOkdllccloxOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKd,,lc,'lO00000kc:dkOkooKMWWNX0kdlco0
MMMMMMMMMMXdokOOOOOOOOOkdlcldkO0KKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKXk,.cxd;cO0000kc;dkOOOdcdxxolc:::::ox
MMMMMMMMMMKodkOOOOOOOOko;:ld0XKKkdkKKKKKkdOKKKKKKKKKKKKKKKKKKKKKKKKKKO:;x0k::k000kc;dOOOkOxlokkkxdlc::cd0
MMMMMMMMMMKodkOOOOOOOOd;cxcoKKKOloOKKKX0lcOKKKKKKKKKKKKKKKKKKKKKKKKKK0l,o0Oocx00kc:dkOOOOOxokNMMWWNK0kxx0
MMMMMMMMMMKodkOOOOOOOOd;oOokKKXxcxKKKKX0ooKKKKKKKKKKKOkO0KKKKKKKKKKKKO:.,dOkxkOkl:dkOOOOOOxokNMMMMMMMMWWN
MMMMMMMMMMKdokOOOOOOOOx:ckOOKKKOod0KKKKKOdxKKKKKKKKOo:':kKKKKKKKKKKKOc,:::clodd:;okOOOOOOOdldXWMMMMMMMMMM
MMMMMMMMMMXxokOOOOOOOOkd:lO0KKKK0O0KKKKKK0O0KKKKKKK0c..o0KKKKKKKKKKOc;okkkxolcccdkOOOOOOkOdcoxOXWMMMMMMMM
MMMMMMMMMMWklxOOOOOOOOOkxcckKKKKKKKKKKKKKKKKKKKKKKKKx;l0KKKKKKKKKKOc:dkOOOOOOOOOOOOOOOOOOkookxdxOKNWMMMMM
MMMMMMMMMMM0odkOOOOOOOOOOxc:dOxx0KOkOKKKK0kk0KKKKKK0dlOKKKKKKKKKKkc:dOOkOOOOOOOOOOOOOOOOOxlkXOddddkOXNWMM
MMMMMMMMMMMNxlxOOOOOOOOOOOkl;cl:o0Oocd0KKOo:o0KKKKOl:dKKKKKKKKKKkccxOOOOOOOOOOOOOOOOOOOOkooKW0xdddxkO0XWM
WNNWMMMMWNX0o:okOOOOOOOOOOOkd:,''dKKd:o0KKKx::clc;',o0KKKKKKKKKxccxOOOOOOOOOOOOOOOOOOOOOdlkNWXkdxxkKNWWMM
OxKWWXKOxxxxkdldkOOOOOOOOOOOOxo;.'o0Kx;:dko:;:llcldkKKKKKKKKKKx:lxOOOOOOOOOOOOOOOOOOOOOxc;cxKX00XKkkXWMMM
llxOxxxkOKNWWNxldkOOOOOOOOOOOOOkxl;:dOk:.,cdOKKKKKKKKKKKKKKK0d:lkOOOOOOOOOOOOOOOOOOOOOxloxc':dOXWWKkkKWMM
ccldOKNWMMMMMMNxldkOOOOOOkOOkOOOkkxc::c,,dKKKKKKKXXKKKKKKKOdc:dkOOOOOOOOOOOOOOOOOOOOOxldKNk;.',lkKNXkx0WM
llldk0NWMMMMMMMNOookOOOOOOOOOOOOOOOkkxl,,d0000Okdddooooolc::lxOOOOOOOOOOOOOOOOOOOOOkd:c0WMKl'...';ok0kx0N
0KKKKXNMMMMMMMMMNx:lxkOOOOOOOOOOOOOOOOko;,;;::c::ccccllooodkOOOOOOOOOOOOOOOOOOOOOOkolc,;dXNx,.'';okOXN0xx
MMMMMMMMMMMMMMMMNkllodkOOOOOOOOOOOOOOOOOkdoodxkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxodKXd. 'od;,dxcl0WWMNkl
MMMMMMMMMMMMMMMMNkd0KdodkOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxooONMMXl.  ..;kX0lcONXkoo
XNNWWMMMMMMMMMMMNkdKWN0xodkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdl;;kWMMMM0,     .:xkocodokX
clodxkO0XWMMMMMMXxxXMMMNxcldxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOkxdodx:.,xNMMMNo.   .cxkK0l:ckNM
c::::ldOKWMMMMMMKdkNMMMNxoOOxddxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxdold0NWO,..:xXWM0,'oc.,ON0olocl0W
xc::lokXWMMMMMMW0dOWMMMXxxXMW0lcoddxkOOOOOOOOOOOOOOOOOOOOOOOOOOkOOkkdoodx00OKNWXc.  .,oKKk0NXo.,lld0N0lcx
NOllO0kxx0NWMMMWOo0WMMWKdkNMMKodK0OxddodxkkkkOOOOOOOOOOOkOkkkxxdolloxOKNWMNOxOXXl.  ..,ckXWMW0l;;oXMMWXd:
WWKOKMWXOxxk0NWNkdKWMMWOd0WMMKdxNMMWNOoldxxddddooddddddooodddxxkOxcdXMMMMMWKxdkOl....cOXXNWXkooo'.oNMWKdc
O0KKXNWWWWXOxxkkdxXMMMNkdKWMW0dkNMMMMXxxKWWNXX0olk00000koo0NNWWMWKc;xNMMMMWXkdddc;dkc'oXWKkookXNk'.l0Ollk
xdddxxkO0KNWWXOdldOXWWXxxXMMW0dkNMMMWXxxXWMMMMXddXMMMMMNkxKMMMMMMKl';xXWMMWXOdddoox0k:,ldodOXWMMWO;':ldKW""", """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXXXXXXXXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0Oxdolccc:::::::::ccclodxk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWXOdc:;;;:ccllloooooooooollcc::;;:cox0XWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWN0xc;,;:lodddddddddddddddddddddddddolc:;;:okKWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMN0dc;;:coddddddddddddddddddddddddddddddddddoc:;:lkXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWXkc;;:loddddddddddddddddddddddddddddddddddddddddol:,:o0NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWXx:,:loddddddddddddddddddddc;;:cdddddddddddddddddddddoc;;o0WMMMMMMMMMMMMMM
MMMMMMMMMMMMWXk:,:lddddddddddddddddddddddc':xx:;ldddddddddddddddddddddoc,;dKWMMMMMMMMMMMM
MMMMMMMMMMMNOc,;ldddddddddddddddddddddddl''xKKd';dddddddddddddddddddddddo:,;xXMMMMMMMMMMM
MMMMMMMMMWXd;;codddddddddddddddddddddddd;.c0KK0c;oddddddddddddddddddddddddo:,c0WMMMMMMMMM
MMMMMMMMW0c,:oddddddddddddddddddddddddl:,lOKKKKo:oxdddddddddddddddddddddddddc,;xNMMMMMMMM
MMMMMMMWO:,coddddddddddddddddddddddl:;:lk0KKKK0c;odddddddddddddddddddddddddddl;,dNMMMMMMM
MMMMMMWO;,cdddddddddddddddddddddl:;;cdOKKKKKXKd;:dddddddddddddddddddddddddddddl;,dNMMMMMM
MMMMMW0:,cddddddddddddddddddddo;,:dOKKKKKKKKKOc;oddddddddddddddddddddddddddddddl,,xNMMMMM
MMMMMKl,cddddddddddddddddddddc,;xKKKKKKKKKKKOc;lddddddddddddddddddddddddddddddddc':0WMMMM
MMMMNx,;odddddddddddddddddddl;cOKKKKKKKKKKKOl:ldddddddddddddddddddddddddddddddddo:'lXMMMM
MMMM0:,ldddddddddddddddddddl;l0KKKKKKKKKK0dccodddddddddddddddddddddddddddddddddddl,;OWMMM
NNNNx,;oddddddddddddddddddc,cOKKKKKKKKKXOl:odddddddddddddddddddddoolc:::c::::::;;:;,oNMMM
xxxd:,cddddddddddddddddddl,;kKKKKKKKKKKXx,,loddddddollcccccclccc::cclloddxxkOOOkl',':KMMM
XXXk:,ldddddddddddddddddc';kKKKKKKKKKKKXk;.,;cccccc:::::clodxkOO000KKXXXKKKKKKKOl,;,;OWMM
MMM0:,ldddddddddddddddo:,:kKKKKKKKKKKKKKKkxkOOOO00000KKKKKXXKKKKKKKKKKKKKKK0kdl::lo;;kWMM
MMMK:,lddddddddooooddl;;o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00Okdolcc::coddo;;kWMM
MMMKl;ldddol:;;;;,,,;;lkKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000Oxdolcc:ccccccodddddddo;;kWMM
MMMXo,;c:;;:cldxo;,;oOKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0xddkxc',;;;,;:clodddddddddddddl,:0MMM
MMWKl',ldxkO000kllk0KKKKKKKKKKKKKKKKKKKKKKKKK0000xl::dOKKkl::oddddddddddddddddddddc'cXMMM
MWKd;':k0000000kldKKKKKKKKKKKKKKKKKKKKKKKOxxddooocldOKKKKKKk:;oddddddddddddddddddo:,dNMMM
WKdlo:,oO000000xcxXKKKKKKKKKKKKKKKKK00K0dcok00000KKKKKKKKKOl';oddddddddddddddddddl,;kXNNW
KdlONk,;x000000xcxKKKKKKKKKKKK0OkxxxkOKOclOKKXKKKKKKXKKOxl;'.;odddddddddddddddddo;,lkkxxk
ooOWMXo,ck0000OdcxKKKKKKKKKKKKK00000KK0dccodxkkkkkkkxolccldo',oddddddddddddddddd:'lKNXOxd
o0WMMWO;'ck0000d:xKKKKKKKKKKKKKKKKKKXKxcd0Oxdodolodddxk0K0x:,cdddddddddddddddddc,c0WMMWN0
0WMMWKdc;,ck000x:dKKKKKKKKKKKKKKKKKKKXOoldkO000000KK0Okdoc;'cdddddddddddddddddc'.lKWMMMMW
WMMW0ooO0o,:xO0kcd0KKKKK0kocd0KKKKKKKKK0kl;coooddxxdoodxxdc;ldddddddddddddddo:,,',dXMMMMM
MMNOlo0WMKl';dOOoo0KKOxl:;;'';ldkO0KKKKKXOlcdOO0000000Okdc:ldddddddddddddddl;,ld;.,xNMMMM
MNkldKWMNOlc:;cxdclo:::cooddoc;;;::clodddo:..,:cccclcccccodddddddddddddddoc,;xKx,..,xNWMM
KdlxXMMWOodKXx:;:,...cdddddddddddolccc:::::ccloooooodddddddddddddddddddoc,,lKWKl....,dXWM
olkNMMWOodKWMWKd;.'..cdddddddddddddddddddddddddddddddddddddddddddddddoc;,''xWWk;''';;:dXW
lkNMMWOodXWMMMW0l::''cdddddddddddddddddddddddddddddddddddddddddddddl:,;ok: 'OXxoxl:xK00XW
xk0NNOodKWMMMW0olOXOo::clodddddddddddddddddddddddddddddddddddddolc,',oKWX:  ,OXNNx:dNMMMM
N0kkxodXWMMMWKolOWMMWXkc,,:cloddddddddddddddddddddddddddddddoc:;;:c,.oNW0,   ,OWWO;lXMMMM
MWKdcoONMMMW0olOWMMMMMXxcloc:;;:clooddddddddddddddddddolc:;;;:lx0X0:..xXd.    'xNK::0WMMM
MNkldkkOXWW0olOWMMMMMNklxXWNXOxl;,;:;;::cccccccccc::;;::cooldKWWMM0;. 'c'    ',:kKo:kWWNK
XklxXWXOkOkoo0WMMMMMNOldXMMMMMWOld0KOkxdoc,':looodo:;dKXNNKxkXWMMWx.    .:x:.oXXKNk:o0Okk""", """MMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMWWWWNNXXXXXXXXXXXNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0OkkxxxxxxxxxxxxxxxxxkkO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWNX0kddddxkkOOO000000000000OOkkxxxxxkOKXWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWX0kdddxkO000KKKKKKKKKKKKKKKKKKKKKKK00OkxddxOKNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWX0kddxkO00KKKKKKKKKKKXXXXXXXXXXXKKKKKKKKKKK0OkddxOXWMMMMMMMMMMMMMMMMMMM
WWMMMMMMMMMMMMMMMWXOdodkO0KKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKK0OkddkKNMMMMMMMMMMMMMMMMM
0XWMMMMMMMMMMMMWXOddxO0KKKKKKKXXXXXXXXXNNNNNNNNNNNNNNXXXXXXXXXXKKKKKK0kxdxKWMMMMMMMMMMMMMMM
KNWMMMMMMMMMMWXOddxO0KKKKKXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKKKK0OddkKWMMMMMMMMMMMMM
kO0KXWWMMMMWN0doxO0KKKKKXXXXXXNNNNNNNNWWWWWWWWWWWWWWWWWNNNNNNNNNXXXXXKKKK0kddONWMMMMMMMMMMM
XK0OkkO0KNNKkodO0KKKKKXXXXXNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNXXXXXKKKK0xoxKWMMMMMMMMMM
MMWWNXKOkkxoox0KKKKKXXXXXNNNNNWWWWWWNK00O00OOOOOOO00KNWWWWWWWWNNNNNNXXXXXKKK0kdd0NMMMMMMMMM
MMMMMMMWXkook0KKKKKXXXXNNNNNWWWWWWXOddxxdddoooolllolc:oXMMWWWWWWWNNNNNXXXXXKKKOddONWMMMMMMM
MMMMMMMNOodk0KKKKXXXXNNNNNWWNXXXKkddk00kxOKKKKK0OOOK0l;OWMMMMWWWWWWNNNNXXXXXKKKOdoONMMMMMMM
MMMMMMW0ddk0KKKKXXXXNNNNWWNOdoolccldxxxoclooddoxOO0KKd;dNMMMMMMWWWWWWNNNNXXXXKKKOdoONMMMMMM
MMMMWXOdok0KKKKXXXXNNNNWWNkox0K00000000000Okd::xKKKKKd,:dOXMMMMMMMWWWWNNNNXXXXKKKOddKWMMMMM
MMWXOxoox0KKKKXXXXNNNNWWNkokKKKKKKKKKKKKKKKKKkcl0XKKKd;dxcoXMMMMMMMWWWWNNNNXXXXKK0koxXMMMMM
NKOkOOdoO0KKKXXXXNNNNWWW0oxKKKKKKKKKKKKKKKKXKKd:xXKKkloOKklkWMMMMMMMWWWWNNNNXXXXKK0ddKWMMMM
kk0NN0dx0KKKKXXXXNNNNWWKdkKKKKKKK0KKKKK0k0KKKKx:oOxdok0KX0ooXMMMMMMMWWWWWNNNXXXXKK0kdkNMMMM
XWWMNkok0KKKXXXXNNNNWW0dxKKKKKKKKOxdddoclOKKKXO:;oxOKKKK0k:;OWMMMMMMMWWWWNNXKXXXXKKOddXMMMM
MMMWXxok0KKKXXXXNNNWWKdd0KKKKKKKKK0kl:l:;xKKKKKd;dKKKKOxddo:lXWWWWNNXK0OkdddolkKXKK0ddKWMMM
MWNKkooOKKKKXXXXNNNNKoo0KKKKKKKKKKKKkkOl:lxKKKK0ock0kddxOKKo;lxxxxxxxxxxkO00k;lKXKK0xd0WMMM
K0O00doOKKKKXXXXNNNKooOKKKKKKKKKKKKKK0dlo:cok000d:cldO0KKKKd:okO0KKKKKKKKKKOl:xXXKK0xd0WMMM
OKNWXxok0kxxdk0XNNKdoOKKKKKKKKKKKKKKKk::coOxoool;;lkKKKKKKkoxKXKKKKKKKKKOxoodOXXXKK0ddKWMMM
WMMWKxlll::c;,:oOkodOKKKKKKKKKKKKKKK0l,lllOK0xoldOKKKKK0kddkKXXKKK00OkdooxOKXXXXXKKOddXMMMM
WWXOxoloxkOOo;;,;lx0KKKKKKKKKKKKKKKKxclkOdllldk0KXKKKOxodOOkxxxxxkkxxkOKXNNNXXXXKKKkoxNMMMM
KOk0K0ddO000x:cdO0KKKKKKKKKKKKKKKKK0xdkKKKOolOKKKK0kdoxkkdodk0KKXNNWWWWWWNNNXXXXKK0xo0WMMMM
k0NWMNkoxO00Ooo0KKKKKKKKKKKKKKKKKKKKK00KKKKOlokOOkddxxdodkKWMMMMMMMMWWWWNNNNXXXXKKOoxXMMMMM
NWMMMWKdok000koxKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OOOkdooodOXWMMMMMMMMMMWWWWNNNNXXXXKK0dd0WMMMMM
MMMMWXOdldO00OdoOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d:ckKWMMMMMMMMMMMWWWWWNNNNXXXXKK0xokNMMMMMM
MWNKOkO0kodO00kod0KKKKKKKKKKKKKKKKKKKKKKKKKK0kdllkNMMMMMMMMMMMMMWWWWWNNNNXXXXKK0xoxXMMMMMMM
N0kk0XWMNOodO00koxKKKKKKKKKKKKKKKKKKKKXKK0kdoox0NMMMMMMMMMMMMWWWWWWNNNNXXXXXKK0xoxXWMMMMMMM
kOKNWMMMMNOodk00kox0KKKKKKKK00KKKKK0OkxdddxOKWMMMMMMMMMMMMWWWWWWWNNNNNXXXXKKK0xokXWMMMMMMMM
XWMMMMMMWN0dooxO0kloOKKXKKOdlc:cllooodkOXNWMMMMMMMMMMMMMWWWWWWWNNNNNNXXXXKKKkddONMMMMMMMMMM
MMMMMMWN0kk0KkddkOkoldOOdl;'cdxxO0KXNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXXXXXKKK0xoxKWMMMMMMMMMMM
MMMMWX0kkKNWMWKxodkOxoc:c:;;:xXNNNNNNNWWWWWWWWWWWWWWWWWNNNNNNNNXXXXXXKKK0koccxKWWMMMMMMMMMM
NWWX0kOKNWMMMMMNOoodkOxlc;;c;c0XXXNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKKK0kdxkx:,:ok0XWWMMMMMM
d0OkOKWMMMMMMMWKkkkkddkkkol::xKXXXXXXXXXXNNNNNNNNNNNNNXXXXXXXXXXKKK0Oxdx0NWN0c'.',:lx0XWMMM
lokKWWMMMMMMWXOk0NWWXOxddl:lk0KKKXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKK0Oxoc,lXWMMMWO:....,lxONWMM
xcckNWMMMMWXOkOXWMMMMWNKOdodkOO0KKKKKKKKXXXXXXXXXXXKKKKKKKKK0Okxxxo,..cXMMMMMNk,';;;dKWMMMM
N0l:oKWWWN0kOXWMMMMMMMMWNkccdxddxkkOO00KKKKKKKKKKKKK000OkkxddkO0Kk;  .oNMMMMMMXd:kKxccxXWMM""", """xxo,..cXMMMMMNk,';;;dKWMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
Kk;  .oNMMMMMMXd:kKxccxXWMMMMMMMMMMMMMWWNXK0OkkxxxxxxxxxkOO0KXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
d.    cXMMMMMMWX0XWWKd:ckXWMMMMMMWNKOxolc:;,,,,,;,,,,,,,,,,;::codk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
.     ;KMMMMMMMMMMMMMWKd:ckNWWNKOdl;,,,,;;::::::::::::::::::;;;,,,;:ldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
o'.,;.'0MMMMMMMMMMMMMMMW0o:lxxl;,,,;:::::::::::::::::::::::::::::::;;,,:okXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
x',0NkoOWMMMMMMMMMMMMMMWWKl'',,;;;;;;;:::::::::::::::::::::::::::::::::;,,:oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;.xWMWWWMMMMMMMMMMMMMWNKx:,,;:::,.,:;'.,::::::::::::::::::::::::::::::::::;,,ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
.cXMMMMMMMMMMMMWNXKOxdl;,,;::::;.'xK0d'.;::::::::::::::::::::::::::;''';::::;,,ckNWMMMMMMMMMMMMMMMMMMMMMMMMMM
OXWMMMMMWNXK0kxollc;'.',;:::::::';kKKKo'':::::::::::::::::::::::::'.;l:'':::::;,,lONWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMKocclodxkOd:',;:::::::::';kKKK0c',:::::::::::::::::::::::,'o0KO:';::::::;,;oKWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMX0KXNWWWXd;,;:::::::::::,,oKKKKk,'::::::::::::::::::::::,'l0KKO:.;::::::::,':ONMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWWWWN0l,,:::::::::::::;.lKKKX0c';::::::::::::::::::::;.;kKKKO;.;:::::::::;,;xNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMN0Oxdoc;',::::::::::::::;.c0XKKKx,'::::::::::::::::::::'.c0KKKk;':::::::::::;,,dXWMMMMMMMMMMMMMMMMMMM
MMMMMMMMKolddl,';:::::::::::::::;':0KKKXO:.,::::::::::::::::::;.'xKKKKx,,::::::::::::;,;xNMMMMMMMMMMMMMMMMMMM
MMMMMMMMWNWWKl,,:::::::::::::::::';OKKKKKd'.;:::::::::::::::::'.:OXKKKo'':::::::::::::;';kNMMMMMMMMMMMMMMMMMM
MMMMMMMMWX0kl,,::::::::::::::::::':OKKKKK0c.,;'....',::;;;;::;..dKXKKKl.,::::::::::::::;'c0WMMMMMMMMMMMMMMMMM
MMMMMMMM0oc:'';::::::::::::::::::,l0KKKKKKx,.'cdxxdc'..,:c::,'.,kKKKKKo',:::::::::::::::,,dNMMMMMMMMMMMMMMMMM
MMMMMMMMNXKo',:::::::::::::::::::,cOKKKKKK0c'l0KKKXKx,,d0K00x,.:0KKKKKo';:::::::::::::::;':0WMMMMMMMMMMMMMMMM
MMMMMMMMMW0c';:::::::::::::::::::';xKKKKKKKxldk0KKKKKxcxKKKKKk:cOKKKKKl';::::::::::::::::,,xNMMMMMMMMMMMMMMMM
MMMMMMMMWNk;,;:::::::::::::::::::.'xKKKKKKK0kc:kXKKKK0oo0KKKKKkcdKKKK0c';::::::::::::::::,'oXMMMMMMMMMMMMMMMM
MMMMMMMMKo;',:::::::::::::::::::;.'xKKKKKKKKKo:dKKKKXKdcxKKKKKOox0KKKO:';::::::::::::::::;'lKWMMMMMMMMMMMMMMM
MMMMMMMMXOl',::::::::::::::::::::''oxolllllll:,;odddoo:'l0KKKKOod0KKKk;,:::::::::::::::::;'cKWMMMMMMMMMMMMMMM
MMMMMMMMMWx,,::::::::::::::::::::'.':odoooooooddxxdddo' ;OKKKXkcoKKKKd,,:::::::::::::::::;'cKWMMMMMMMMMMMMMMM
MMMMMMMMMWk;,:::::::::::::::::::;..;kKXKXKKXXKKKKXXX0o'.;OKKKKx;lKKKKo',:::::::::::::::::;'lXMMMMMMMMMMMMMMMM
MMMMMMMMWXx;';::::::::::::::::::'.:OKKKKKKKKKKKKKK0xc:c;l0KKX0l,dKKKKl';:::::::::::::::::,'dNMMMMMMMMMMMMMMMM
MMMMMMMM0oc;';:::::::::::::::::,.;kKKKKKKKKK0OkxoccldOd;oKKKKk;:OKKK0c';::::::::::::::::;,;kWMMMMMMMMMMMMMMMM
MMMMMMMMNKKd,,::::::::::::::::;..lKXKKKKKKKKd;;loc;cll:,cx00x::kKKKKk,.;::::::::::::::::;'lKWMMMMMMMMMMMMMMMM
MMMMMMMMMMWKc';:::::::::::::::'.,kKKKKKKKKK0d;:ldkkdookko:;;;ckKKKKKl.'::::::::::::::::;';kNMMMMMMMMMMMMMMMMM
MMMMMMMMMMWNx,,;::::::::::::::'.c0KKKKKKKKKKK0Oxl:d0XKKKK0kkOKKKKKKO;.,::::::::::::::::,'oXWMMMMMMMMMMMMMMMMM
MMMMMMMMWXOxc,',::::::::::::::,.,d0KKKKKKKKKKKKK0dcxKKKKKKKKKKKKKKKx..;:::::::::::::::;'c0WMMMMMMMMMMMMMMMMMM
MMMMMMMM0lcldxc',::::::::::::::,..:x0KKKKKKKKKKKK0dd0KKKKKKKKKKKKKKo.':::::::::::::::;':OWMMMMMMMMMMMMMMMMMMM
MMMMMMMMXKXNWWKl,,;::::::::::::::'..:x0KKKKKKKKKKK00KKKKKKKKKKKKKKO:';::::::::::::::,':OWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWXd,';::::::::::::::;'..;d0KKKKKKKKKKKKKKKKKKKKKKKK0c',::::::::::::::,'c0WMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWNk:',:::::::::::::::;'..cOKKKKKKKKKKKKKKKKKKKKKKk:',:::::::::::::;,,oKWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWWWNX0xc'.';:::::::::::::::;..dKKKKKKKKKKKKKKKKKKK0d;'',::::::::::::;,,ckNWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMNOxdoc:;'..;lc,,;::::::::::::::;'c0KKKKKKKKKKKKKKKKK0o'.,::::::::::::;,,:dKWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMXxc,.....;dKNXOl;,;::::::::::;,'.:OXKKKKKKKKKKKKKKKK0l..;::::::::::;,,:dKWWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWXkc,...cOWMMWXOc,,,,;::::;'',;;,cOKKXXXXXKKKXKXKKKXKx. ..,;::::;;,,cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMKocdo;,oKNXKOdc;:d0kl,,;;:,.,dkoclodxxdddxxxxxxxxxdddl,';;',;;,,,:oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMKOXWKddxdl:;,',cONXOo,,::;,..lOOOOkkkkxdddddddddddddxxxxko'.,;cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMOlkNWX0ko;'''';odl:'.,dKXOxo::ccloodxkkkOOkOOOOkkkxdolc:cc;.'dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMKc'ckXNOl:;,''''....;kNWMMWWN0o;;lolcccc::ccccc:,'.,ldx0XNk. 'xNMMMMMMMMMWNKK0XWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWNkc,clcoOKdcc;,,,,:kNMMMMMNOo:cONWNNXOxoxOOxl,....dXWMMWM0'  .c0WMMMMMMMWXx;.oNMMMMMMMMMMMMMMMMMMMMM""", """kOOxc'...';codO0KXNWMMMMMMMMMMMMMMMMNd.;OKK000000000KKXNWWMMMMMMMMMMMMMMMMMMMMWKxxO00OO0NMMMMM
NWWXo';k0Oxolc;;,;::cldxkO0KXXNNX0kdl;. ..............',;cldk0XWMMMMMMMMMMMMMMMWNXXXXXNWMMMMMM
O0k:,lKWMMMMWWNXK0kxollc:;;,'',,..........'''''''''''.........':lkKNWMMMMMMMMMMMMMMMMMMMMMMMMM
'.. .cdkOKNWWWMMMMMMWWWWXOl'.  ...''',,,,,,,,,,,,,,,,,,,,,,''......;oONWMMMMMMMMMMMMMMMMMMMMMM
c.;ddl:;;;;;:lodkOKXNNKx:. ....''',,,;;;;;;;;;;;;;;;;;;;;;;;,,,,''....,o0NMMMMMMMMMMMMMMMMMMMM
,oXWMWWNXKOkdoc:;;;,,,......;cll:;',;;::::::::::::::::::::::;;;;;,,,'....:kNMMMMMMMMMMMMMMMMMM
'oxO0KXNNNWWWMMWNKd'  ..','':x0KKOo;,;:ccccccccccllccccccccc:::::;;;,,,'...;kNMMMMMMMMMMMMMMMM
::::;;;;;::clooddc....',,,;;,,lOKKKOl;:lllllllolloolllllllllcccc::::;;;,,'...:ONMMMMMMMMMMMMMM
WWNNXK00Okxdol;.  ..',,;;;;::;;dKKKK0l,cooooodddddddoooooooollllcccc::;;;,,'...lKWMMMMMMMMMMMM
MMMMMMMMMMMMWO:...',,,;;:::cc:;cOXKKKk:;odddxxddocccclo..d.do..llllccc:::;;;,...,kNMMMMMMMMMMM
O0KKXNNWMMMNx' ..',,;;:::cccll:;xKKKKKo:lxxxxkxooxOOxlccloddddo.oolllccc:::;;,'. .oXMMMMMMMMMM
;;;;;:::cll:. .',,;;;::ccclllol:l0XKKKOlcxkkxoox0KKKKKOxl::oxxxd.dooollccc::;;;,...lXMMMMMMMMM
NNXK0Okxdc.  .',,;;:::cclllooooccOXKKXKdcoxoodOKKK0OKXKKKOl:dkxx.dddoolllcc:::;;,...cXMMMMMMMM
MMMMMMMMWd. .',,;;:::cclloodddo:o0XKKKKOc:ok0KKKKX...0O0Kxcokkkx.xddooollc:;,,',,...oNMMMMMMM
WMMMMMMM0, .',,;;::cccllooddxxl:xKKKKKKKdlxKKKKKK....ook0KxcdOO.kx.ddolllclloddl,',...kWMMMMMM
ooodddxx:...,,,;:::ccllooddxxxlcOXKKKKKX0dcd0KKKOdlkKxo0XKxco....l..odxxkO00KKXKk;.,,..;KMMMMMM
olllc::'. .',,;;::ccllooddxxkxccOXKKKKKKKKkkKKKK0OxdOOolxkoldx.xkOO0KKKKKKKK0kxo:,;;,'..xWMMMMM
MMMMMMXo...,,;;::ccllooddxxxkkllOKKKKKKKKKKKKKKKKK0dlx.....OKXXKKKKKKK0kxolc::::::;;,..:KMMMMM
MMMMMMX:..',,;;::ccllooddxxkkkllOKKKKKKKKKKKKKKKKKK0xk.KKKKKKKXKK0kxdolllllollcc::;;,. 'OMMMMM
WWWWWW0, .',,;;:ccclooddxxkkOOocOKKKKKKKKKKKKKKKKKKKOdkKKKKK0Okddddddxxxxddoollcc::;;'..kWMMMM
ccc::c;. .,,;;::ccllooddxxkkOkc:OXKKKKKKKKKKKKKKK0O0KxokOkxxkxdddxxdddddolcc:::::;,;;'..dWMMMM
xxxxxxl. .,,,;::ccllooddxxkkOx:cOKKKKKKKKKKKKKKX0xx0Xkc;clodxdddddddxkkOOOOOOOOOOx;','..dWMMMM
MMMMMM0, .',;;::ccllooddxxkkOd;c0KKKKKKKKKKKKKKKkxOKKKxclkO00KKKXXXKXXKKKKKKKKK0kl,','..xWMMMM
MMMMMMK; .',;;::ccllooddxxkkOo;dKKKKKKKKKKKKKKX0xOKKKXKxd0KKKKK0kkkkkkkxdodxdlc:;,;;;'.'OMMMMM
WMMMMMNl..',,;;::ccllooddxxkkl:kXKKKKKKKKKKKKKKOxOXK0KKkoxOkxxxxdxkkxkkOOOOkl;:::::;,..;0MMMMM
kOO0KKKd...,,;;::ccllooddxxkxlo0KKKKKKKKKKKKKKK0O0KKkx0KxlxkkOKKKK0OOOkxdol::ccc::;;,..oNMMMMM
;;;::clc...',,;;::ccllooddxxdlxKKKKKKKKKKKKKKKKKKKKKkoxOdlkOkxxxxdlloolllllllccc::;,. 'OMMMMMM
;;;coxO0d. .,,;;::cccllooddxooOXKKKKKKKKKKKKKKKKKKK0xloo:;lddxxdxxkkxxdddoollcc::;;'..oNMMMMMM
cokKNWMMNo...,,;;::cclllooddodOXKKKKKKKKKKKKKKKKKKKOl::ldk0000OOkkkxxddooollcc::;;,. :KMMMMMMM
OKXNNNNNN0;..',,;;::cclllooolo0KKKKKKKKKKKKKKKKKKKKKd;lk000OOOkkkxxxddoolllcc::;;,. ,OWMMMMMMM
d:;:c:cc::,....,,;;::ccclloc:xKKKKKKKKKKKKKKKKKKKKKKdck0OOOkkkkxxxddooolllcc::;;,..,OWMMMMMMMM
k:......,cxkc...,,;;;:ccclc;l0XKKKKKKKKKKKKKKKKKKKKOclxOkkkkxxxdddooolllcc:::;;'..;0WMMMMMMMMM
cc;...':xO00x,. .',;;;,,;:;:xKKKKKKKKKKKKKKKKKKKKKOlcdkxxxxxxdddooolllccc::;;,...cKMMMMMMMMMMM
XXo,,,',,,,,;::,...,,',:::;o0KKKKKKKKKKKKKKKKKKK0xcldxxxdddddoooolllccc:::;,'..'xNMMMMMMMMMMMM
XOc;:,'''';lkKNXd'....cxxookKKKKKKKKKKKKKKKKKK0klclddddoooooollllccc::::;;'...lKWMMMMMMMMMMMMM
ccodkx:';oONWMWMWKo' .:k0OxddxOKKKKKKKKKKKK0Odl:clooooollllllcccc::::;;,'...cOWWMMMMMMMMMMMMMM
,dXWWKod0NWWNNXK0Ox:...,lkOOkxdxxO0KK0kOKX0o;;:cllllllllcccccc::::;;;,'..,o0WMMMMMMMMMMMMMMMMM
c,oKWNXX0xocc:;;,'':dOx:'';oxOOOxddxkO0KKKO;':cccccccccc::::::;;;;,....:xXWMMMMMMMMMMMMMMMMMMM
Xx;;kNWNKx:'....'ckXWWWNOl'..,coxOOkxxxkO0O;';:::::::::;;;;;;,'.....,oONMMMMMMMMMMMMMMMMMMMMMM
MW0l,:ddlc::,..':dkxxddol::cll;,',;:ldxdddl,.'',,;;;;,,,,'......;oOKNWMMMMMMMMMMMMMMMMMMMMMMMM
X0xc,...ckKOc;lkdc,'''',;lOXWWNKOxl;'.'',''...............,:lx0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
::cokOd:;oKKxkK0xc;,'',lONWXK0000OOkdoloddolc' .,cloodxO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""", """MMMMMWk:lxKNWMMMMMWKkoccoOXNKkc'..,,'''''''...''''...':cdk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMWKxlccd0NWMMMMMWXk:.','..',;::clllllllllll:,'...',,,,;coOXWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMWXkl:cd0NWWN0o:'..,:cllooooooolloollol;',ldxkkOOOxoc;,,cd0NMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWXkdccll;..,:clooooooooolloooollll:.',',;::cdk000Oko:',cxKWMMMMMMMMMMMMMMMMM
MMMMMMWWMMMMMMWNx'..':llooollooooolllooooooll:'.';cdkxd:,;oO0000Oko;',o0NMMMMMMMMMMMMMMM
MMMMMWklxKNWWNOc..;clloooooooooloolllc:;;;;;:clxO0KKKKKKkl;:dO00000Oxc''lKWMMMMMMMMMMMMM
MMMMMW0l;;:odc'.;cloooloooooooolc:;;,,;:codk0KKKKKKKKKKKKKx;,oO000000Oxc',dKWMMMMMMMMMMM
MMMMMMMWXOc...,cloooloooooolol:,,:oxO00KKKKKKKKKKKKKKKKKKKKOc,oO0000000Od;.;kNMMMMMMMMMM
MMMMMMMMWO;.':loloooolloooolc;'ckKKKKKKKKKKKKKKKKKKKKKKKKKKKOc;d000000000kl'.lKWMMMMMMMM
MMMMMMWNx'.,colloooooolooolc,;xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk;:k000000000Ox;.:0WMMMMMMM
MMMMMWk;..;looloooooooooloc':kKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl,oO0000000000k:.,OWMMMMMM
MMMMMWd..;llooloolollooool,,xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKx;cO0000000000Od,.,OWMMMMM
MMMMMWo.,lloooooooolloooo:.:0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKd';O00000000Oxl;;'.;0WMMMM
MMMMMWo'cooooooooooolooll;'lKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkl'.;O000000Oxc:cllc'.lXMMMM
MMMMMWx:loooooooooooooool;,dKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKx;;c';k00000kl:cllool:.'kWMMM
MMMMMWklooooooooooloooloc';kKKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKo,okc:k000koc:loollool,.cXMMM
MMMMMWOloloooooooooooool:'c0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o';xdlxOkl:clllooooooo:.,OWMM
MMMMMWOooooooooooooollol;'o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0l.:kxoc,;clooooooooooc'.dWMM
MMMMMWOoooooooooooooolol,,dxxKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKO:.,;',:looooooolooool,.lNMM
MMMMMWOooooooooooooooooc';kkdOKKKOoxKKKK00KKKKKKKKKKKKKKKKKKKx'.':lolloolooooooool,.cNMM
MMMMMWOooooooooooooooooc':0OkOKKX0olOKKKkokKKKKKKKKKKKK00KKKK0l.;looollloooooooool,.cNMM
MMMMMWOoooooooooooooloo:.c0d,;kKKK0xx0KK0kkKKKKKKKKKKKkloOKKKKo.'lollooooooooloool,.lNMM
MMMMMWOooooooooooooolll;.lKO:'xKKKO:cOKKKkdOKKKKKKKKK0l'cOKKKKo.'lollooooooooooooc'.dWMM
MMMMMWOlooooooooooooool,.lK0l:kKKKOoo0XKKd,oKKKKKKKKXk;;kKKKKO:.,looolloooooolooo:.,OWMM
MMMMMWOlooooooooooooool,.lK0ccOKKK0dd0KKKOcl0XKKKKKKKd,lKKKKO:.,clooooooooooolool,.cXMMM
MMMMMWkcoooooooooolllol'.oKO:l0KKXOoxKKKKKdlOKKKKKKK0l,xKK0d,.,lolooooooooooolol:..xWMMM
MMMMMWo;loooooooooolooc''d0d;dKKKXkcxKKKKKxlkKKKKKKX0c;x0d,.':looooooooooooooooc'.cXMMMM
MMMMMWl.;loooooooooooo:.,k0c:OKKKXx:xXKKKKx:o0KKKKKX0c';,.':llolooloooooooooool,.;0WMMMM
MMMMMWo..:loooooooooll;.c0x;oKXKKKo;xXKKKKk:l0KKKKKXO:..;clooolooooooooooooolc,.,kWMMMMM
MMMMMMXo..;loooooolool,,x0o:xKKKK0l;kXKKKK0c:OKKKKKXO;,colooooooooooooooooooc,.,kWMMMMMM
MMMMMMWNx'.,llloooloo:.;OO:c0KKKXO:;kXKKKXKl;xKKKKKXk,,lllooooooooooolooool:'.;OWMMMMMMM
MMMMMWOll;..':lolooooc..ll,oKKKKXk;:OKKKKK0c,dKKKKKKd,;ooooooooooooooololl;..lKWMMMMMMMM
MMMMMWx:cool'.,clollolc;,.,kKKKKXx;l0KKKKKd..dKKKKK0o':oooolooooooooooll:'.;kNMMMMMMMMMM
MMMMMMNXNWWW0l'.;clollolc..dKKKKO:,xKKKKKO: .xKKKKK0l,cooooooooooolool:'.,oXWMMMMMMMMMMM
MMMMMMW0ddk0KXkc'.,cloool;.;kKOd,.;OKKKK0o'.,kKKKKKO:;loooolloollool:'.,oKWMMMMMMMMMMMMM
MMMMMMXOo;',:cooc...';clol:',;,''.;OKKKKd,'.;kKKKKx:;coooooloololc;'.;dKWMMMMMMMMMMMMMMM
MMMMMW0oo:,'''',;:cc;'.';cllc:clc..oOOxl;;:''oOkdc,,cooloooollc;'.'ckXWMMMMMMMMMMMMMMMMM
MMMMMMWNOc,;cox0KXNWN0d:'..,;:cll:'',;,;cll;..''',:lloollc:;,.',cxKWMMMMMMMMMMMMMMMMMMMM
MMMMMMMXkxOKXWMMMMMMMMWN0o;','..';;::cllooollcccclcc::,'..';cdOXWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWWWMMMMMMMMMMMWWX0xdOKKkdl:,''''''''''''''',,,;:ldkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWNKOxddxKWMMMWNXK0kxddddddddxkOKXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""", """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0KNWNNNXKOk0XNXXOkKNWWWWXO0XWMMMMMMMMMWXOOXWNKXWMMMMMMWKc
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkkO0000000O000000OO0000KK0kkKWMMMMMMMWKO0NWMMMMMMMMMMMMWk
MMMMMMMMMMMMMMMMMWNNNWMMMMMMMMWNXNNNWWXKKKXXXXXXXXXXXXXXXXXXKK000Oxx0NWMMMMWKk0NMMMMMMMMMMMMMMMX
MMMMMMMMMMMMMMMMMWX0k0XWMMMWNK0OO0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0OO0KXWNKk0NWMMMMMMMMMMMMMMMW
MMMMMMMMMMMMMMMMMMMWXOk0XNK000KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK000Ok0NWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWN0kkO0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK0O0XWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNKNMMMMWN0O0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK00XWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMKodKWWNKO0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK00XWMMMMMMMMMMMMM
MMMMMMMMMMMMMXxclk000KXXXXXXXXXXXXXXXXXXXXXX0kxxxkkdllox0KXXXXXXXXXXXXXXXXXXXXXXK00NWMMMMMMMMMMM
MMMMMMMMMMMMMMWXkdOKXXXXXXXXXXXXXXX0dlccc::;'...';;..,:cccd0XXXXXXXXXXXXXXXXXXXXXX0OKWMMMMMMMMMM
MMMMMMMMMMMMMMWX00XXXXXXXXXXXXXKkoc,.,:cloolllcc::cllloddl;:xKXXXXXXXXXXXXXXXXXXXXXKOKNMMMMMMMMM
MMMMMMMMMMMMMWX0KXXXXXXXXXXXXKklcloooooolllllloddoodxkkkdooooodOKXXXXXXXXXXXXXXXXXXXKO0NWMMMMMMM
MMMMMMMMMMMWWX00XXXXXXXXXXXX0o:o0KKKKKKKK00Okxddddx0K00K0xlldxl:lOXXXXXXXXXXXXXXXXXXXKO0NMMMMMMM
MMMMMMWXXWWN0O0XXXXXXXXXXXXkcckKKKKKKKKKKKKKKKKKKKKKKKkolxOkloOx::OXXXXXXXXXXXXXXXXXXXKO0NMMMMMM
MMMMMMNxoONXO0XXXXXXXXXXX0ocd0KKKKKKK0O0KKKKKKKKKKKKKK0OxllOkox0d,lKXXXXXXXXXXXXXXXXXXXKOKWMMMMM
MMMMMMNd;:oxOKXXXXXXXXXXk::kKKKKKKKK0o:x0KKKKKKKKKKKKKKKK0ooOO0K0:;kXXXXXXXXXXXXXXXXXXXX00XMMMMM
MMMMMMWKxdod0XXXXXXXXXXKo,dKKKKKKK0d;..,:ldxO0KKKKKKKKKKXKOk0KKKKo,oXXXXXXXXXXXXXXXXXXXXKOKWMMMM
MMMMMMMMWNKOKXXXXXXXXXXXk;l0KKKKKK0l':ol'.''':xKKKKKKKKKKKKKKKKKKk;;OXXXXXXXXXXXXXXXXXXXX00NMMMM
MMMMMMMMMN00XXXXXXXXXXXXKd;o0KKKKKKd;oxo,;oc..l0KKKKKKKKKKKKKKKKKKo,c0XXXXXXXXXXXXXXXXXXXKOXMMMM
MMMMMMWKKXO0XXXXXXXXXXXXX0l;xKKKKKXd,cd:..;:c,.o0KKKKKKKKKKKKKKKKK0o,lKXXXXXXXXXXXXXXXXXXKOKWMMM
MMMMMMNo,cd0XXXXXXXXXXXXXXO:;kKKKK0c..,,;ldOKd,oKKKKKKKKKKKKKKKKKKK0o,l0XXXXXXXXXXXXXXXXXKOKWMMM
MMMMMMWOold0XXXXXXXXXXXXXXXk,,x00x;.'ldOKXXXXx;oKKKKKKKKKKKKKKKKKKKKKd:cOXXXXXXXXXXXXXXXXKOKWMMM
MMMMMMWWWNO0XXXXXXXXXXXXXXKd'';::;clclxKXXX0d,'dKXKKKKKKKKKKKKKKKKKKKKkc:dKXXXXXXXXXXXXXXKOKWMMM
MMMMMMNkx0OOXXXXXXXXXXXXXX0:,xOkkOKK0d;lOOoc:lk0KKKKKKKKKKKKKKKKKKKKKKK0d:cxKXXXXXXXXXXXXKOKMMMM
MMMMMMNo,;lkKXXXXXXXXXXXXX0::OKKKKK0kd;.;ldk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKOl;cooc:cokKXXXX00XMMMM
MMMMMMW0xxxx0XXXXXXXXXXXXX0:;OKKKK0o;',cx0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKk;.,:llc:lkKXX0KNMMMM
MMMMMMWXXWN0OXXXXXXXXXXXXX0;,kKKKKK0kxOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkl:ok000Okl:cdkOXWMMMM
MMMMMMNo:xKKO0XXXXXXXXXXXXO;;OKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d:ck00000000ko:lONMMMMM
MMMMMWNl.':dxkKXXXXXXXXXXX0:,xKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o;lk0000000000OxkXWMMMMM
MMWKxlc,....,ckKXXXXXXXXXXXk:;o0KKKKKKKKKKKKKKKKKKKKKKK0kkO0KKKKKKKKKKOl:dO0000000000OkkXWMMMMMM
MWXkdoooooolcldOKXXXXXXXXXXX0c':oxkkkkkkkxolc::;;;;;;;,'',;;cdk0KKKKKOllx00000000000OkkXWMMMMMMM
MMMWWWWWWWWWWNX0OKXXXXXXXXXXXKOxoooooooooolloddooddoodddkOOkoc;:d0KKkloO00000000000OkOXWMMMMMMMM
MMMMMMMMMMMMMMMNKO0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKOoclxdcoO00000000000Ok0NWMMMMMMMMM
MMMMMMMMMMMMMMMMWKkOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkc;oO0000000000OkOKWMMMMMMMMMMM
MMMMMMMMMMMWNXKOxl:lk0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk:lO000000000OOO0NWMMMMMMMMMMMM
MMMMMMMNKkdoc:;,',l0XK00KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO:ck00000000OOO0XWMMMMMMMMMMMMMM
MMMMMMMNKko:,'',;xXWMWNK00KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKl.lO000000OOO0NWMMMMMMMMMMMMMMMM
MMMMMMMWXOdlc,':kNMMMMMWNX000KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXd,'coxkkOO0XNWMMMMMMMMMMMMMMMMMM
MMMMWNKxookK0cc0WMMMMMMMMMWNK000KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0dl::oOKNWMMMMMMMMMMMMMMMMMMMMM
WWWXkoox0NMMXOKWMMMMMMMMMMMMMWNXK0000KKXXXXXXXXXXXXXXXXXXXXXXXKK00000KNWMMMMMMMMMMMMMMMMMMMMMMMM
kOdodOXWMMMMMMMMMMMMMMMMMMMMMMMMWWNXKK000000KKKKKKKKKKKKK000000KKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
;cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXKKKKKKKKKKKKKXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""", """MMMMMMMMMMMMMMMMWWMWWX0kxOXWMMMMW0loKNNXKOxc;okkkkkd::xKNNWNx:dNMWOcdXMMMKlcKWMMMMMMWWWWWWWWWWN
MMMMMMMMMMMMMMMMNXWMMWWKOx0NWMWNKkc;clllllllllllllllccllllodl;c0NWKllKMMMNdcOWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKkXMMMMWNKO0KOxocllodxkOOOO0000000000OOOkxxdocclokkc:OMMMWOcdNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM0lxNMMMWXOdcclodkO000000000000000000000000000OOkdoc,,dXWMMKclKMMMMMMMMMMMMMMWNX
MMMMMMMMMMMMMMMMXocxNNKxlcldkOO000000000000000000000000000000000Odcclcld0NXdckWMMMMMMMMMNKkdoc:
MMMMMMMMMMMMMMMMWNOdoocldkO0000000000000000000000000000000000OxolldO0Oxlcokd:oNMMMMMMMMMNKko:,'
MMMMMMMMMMMMMMMMMNOl:okO0000000000000000000000000000000000OxolclxO00000Okoc:,c0WMMMMMMMMWXOdlc,
MMMMMMMMMMMMMMMMXdcokO0000000000000000000000000000000000ko:coxOO000000000Oko:;xNMMMMMWNKxookK0c
MMMMMMMMMMMMMMMMKdxO00000000000000000000000000000000000kc;okxol::cldxO00000OklcxXWWWXkoox0NMMXO
MMMMMMMMMMMMMMMMN00000000000000000000000000000000000000d;:kd,.;lddollloxO0000OdclkOdodOXWMMMMMM
MMMMMMMMMMMMMMMWN00000000000000000000000000000000000000k:';clx0KKXKK0kolldkO00Okl;cxKWMMMMMMMMM
odOxox00xxxxx0KXK000000000000000000000000000000000000Oxo:,lkKKKKKKKKKKK0kolldO00kocxXMMMMMMMMMM
o,'..,xK0d:;ok00000000000000000000000000000000000Oxollldk0KKKKKKKKKKKKKKKKOo;;lkOOo:xNMMMMMMMMM
l,....;ONkclk0000000000000000000000000000000OkdollloxOKKKKKKKKKKKKKKKKKKXKKO:..':odc:kWMMMMMMMM
o:,'...:occk0000000000000000000000000OkxdllcccloxOKKKKKKKKKKKKKKKKKKKKKKK0d,..'.....'c0WMMMMMMM
WNKkxl;'';dO0000000000000000000OxolccccclodxO0KKKKKKKKKKKKKKKKKKKKKKKKKKKk;.,,,,,,,;,;dNMMMMMMM
0NOxXNKo;ck0000000000000000Oxoc::cloxO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo..;;;;;;:::;c0WMMMMMM
:lc;dNNd:dO0000000000000Oxl;;cokOxdxOK00OdlkKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo.,odddddxkko:xNMMMMMM
l,'';x0l:x0000000000000kl,:okkxdodxO0d:;:cd0KKKKKKKKKKKKKKKKKKKKKKKKKKKKXx',x00000000xcoXMMMMMM
,'''';c:ck00000000000Ox;':ollodk00Oxl::ok0KKKKOo:cxKKKKKKKKKKKKKKKKKKKKKXk,,x00000000kllKMMMMMM
koc;,'',ck000000000Okl'.'coxO00kdoloxOKKKKKKOo;,cx0KKKKKKKK00KKKKKKKKKKK0l,lO00000000Olc0MMMMMM
MWNKko;,lk00000OkdlcccldO00OdolodO0KKKKKK0kl:cdOKKKKKKKKOdccdOKKKKKXKKK0o':k000000000Olc0MMMMMM
MMMMMNOcck000kl;;cdk000Oxolodk0KKKKKKKKOdlldkKKKKKKKKKOoccdOKKKKKKKKKKkc,ck0000000000kllKMMMMMM
MMMMMMXl:x00k:.ck00kdlcloxOKKKKKKKKKOxlcokKKKKKKKKKKkoldOKKKKKKKKKK0xc;cxO00000000000xcdXMMMMMM
NWWWWWNd:dO0kc,coc;:cok0KKKKKKKKKOxolox0KKKKKKKKKK0l:oOKKKKKKKKKKOo:,:dO000000000000OockWMMMMMM
clloooo:,ck00x;.'lk0KKKKKKKKK0kdlclxOKKKKKKKKKKKKk:'o0KKKKKKK0xxo;;lxO00000000000000kll0MMMMMMM
.....';c::dO0k:..o0KKKKKKKOdlc:lxOKKKKKKKKKKKKOdc'.;kXKKKKKKOc';cdO0000000000000000Oo:xNMMMMMMM
..';oOXN0ccx0Ox;..,ldddlc::cox0KKKKKKKKKKK0xoc::lo;;kKKKKKK0c.,lk000000000000000000xclKMMMMMMMM
;okXWMMMNk:lk00Oxl:;;;...lOKKKKKKKKKKK0kdc::cdkO0Oc'oKKKKKOc,ck0000000000000000000kccOWMMMMMMMM
XWWMMMMMMNx:lk00000OOOd''oOKKKKK0OxdolcccoxO000000x:,codoc;;oO0000000000000000000klckNMMMMMMMMM
MMMMMMMMMMNxclk0000000Ox:;;;:clcc::cldxO00000000000kdlcccldk0000000000000000000OklckNMMMMMMMMMM
MMMMMMMMMMMNOccxO00000000OxdddxxkOO0000000000000000000000000000000000000000000OxclOWMMMMMMMMMMM
MMMMMMMMMMMMWKocok00000000000000000000000000000000000000000000000000000000000koco0WMMMMMMMMMMMM
MMMMMMMMMMMMMMNkllxO0000000000000000000000000000000000000000000000000000000OdclkNWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWKxllxO000000000000000000000000000000000000000000000000000OxllxKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWKxlldk00000000000000000000000000000000000000000000000OdlcxKWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWKxlloxOO0000000000000000000000000000000000000000OkoclxKWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWNOdlloxOO0000000000000000000000000000000000OkdllokXWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXOdllodxOO0000000000000000000000000OkxdolodkKNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdllloodxkkOOOOOOOOOOOOOkxxdolllodOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0kxddoooolllllllllooooddkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXKKKKKKKKKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""", """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
dxkKWN0kOOxdddddxKWMMMNOxkXMMWNXNNNXK0OkxkkkkkkkkddkO0KXNKkxKWMMMMXxdKWMMMWKdkNMMWKxxXN0xdxoxX
'cONWWOloOkc,',';kWMMMW0lc0WNKkdooollllllllllllllllllllool;;dKNWWNk;lKWMMMNo,dNMMXo,dNWXkc''lK
::OWMWNklxKOc;,,;xNMMMMWOloxolllloodddddddddddddddddddddoolllloxkOc;kWMMMW0::0WWNx;lKWMWKl,;:l
O:c0NKKOlclc:od:,oXWWXOxlcclodddddddddddddddddddddddddddddddddollc;:xXWMMNd;oNWW0::OWWWNd,cO0d
Nx;l0Ooc:;;;:xXOlck0xllloodddddddddddddddddddddddddddddddddddddddoollox0N0::OWWXo;xNMMWO:;OWMN
MXo;xXKkl;;;:xNNOc:clodddddddddddddddddddddddddddddddddddddddddddddddollol,oXWWk;lKWMWKc,dNMMM
MW0c:OWN0d:;;d0Ooclodddddddddddddddddddooooooooodddddddddddddddddddddddol:;oXW0c:OWMMNx,cKWMMM
MMWk;l00xOOo;:ccloddddddddddddddddddolc;,,,;;,,,:odddddddddddddddddddddddolcoko;dNMMW0:;kWMMMM
KO0Oc';,,kNOc;loddddddddddddddddddo:,:loxkkOkxoc',lodddddddddddddddddddddddoc;'c0WMMNo,oXMMMMM
0l;,'...;kOlcodddddddddddddddddddl,'lOKKKKKKKKKKx;'coddddddddddddddddddollcccc:l0WMWO::OWMMMMM
WXk:....'cllodddddddddddddddddddd:'o0KKKKKKKKKKKKOc,:oddddddddoolllccc::cloxkOOdoONXo,dNMMMMMM
MMWXd;...;ldddddddddddddddddddddo:cOXKKKKKKKKKKKKKOc':odddol:;,;:lodddxkO000000Odokk::0WMMMMMM
MMMMW0l',lddddddddddddddddddddddlcd0KKOdd0KXKKKKKKKk;,lddo:..,codxO0000000000000Odl;,dNMMMMMMM
MMMMMNxcldddddddddddddddddddddddc:xKK0x,.;ok0KKKKKOo,,clc:..,;;;;,;lk000000000000Od,;OWMMMMMMM
MMMMWKocoddddddddddddddolccc::::,,dKK0xdddlcclllll;......':dOOO00Od::oO00000000000Ool0WMMMMMMM
x0NWNxcoddddddddddddl:,,,,;:::;'..dKKKKXKKK0Okkkkkkkdlc;,;oxxxOKKKKOl,ck00000000000xlkWMMMMWWW
',:oo:cddddddddddoc;,;cdO00KKKKd.'kXKKKKKKKKKKKKKKKKKKxc,';:cc:lkKKK0o,ck0000000000OooOK0Oxdol
:ccc;;ldddddddddo;,lk0KKKKKKK0d;.'d00KKKKKKKKKKKKKKKKOkkO0KKKKkllOKKKKo,lO0000000000x::lllodxk
NNWXocoddddddddd:,oKKKKKKKK0d:,,..,:::d0KKKKKKKKKKKKKKKKKKKKKKKK00KKKKOc;d0000000000OloKNWWWMM
MMMXocdddddddddo;:OKKKKKKOd,..',;okOkc,o0KKK00000KKKKKKKKKKKKKKKKKKKKKKx:cO000000000OdxXWMMMMM
MMMXocdddddddddo;l0KKKOxoc' .,lk0KKKKk;;k0xc::::;:xKKKKKKKKKKKKKKKKKKKK0l:x000000000OddKWMMMMM
MMMXocdddddddddo:c0KKKOkkd;;o0KKKKKKKk;ckl,cxOOOx;,dKKKKKKKKKKKXKKKKKKK0c,o000000000OddXMMMMMM
MMMXdcoddddddddo::kKKKKKx;cOKKKKKKKKkclxl;d0KKKKKk;:OKxc::lx0KKKKKKOdll:..oO0000000OxlxNMMMMMM
MMMNxcodddddddddl;l0KKX0:;kKKKKKKKOocokl:xKKKKKKK0c:kk;:dd:':kKKK0o;;coo,,x000Okxolc;;kWMMMMMM
MMMW0lldddddddddo:;xKKXO:c0KKKKKOd;.,c::kKKKKKKKX0l:dccOKK0l':OK0c,oO00d,:k0Odc:::clcl0WMMMMMM
MMMMXocodddddddddl,:kKXOcl0KKKK0Oxdo:':kKKKKKKKKKOcll:dKKKK0c'd0l.:k00Oo;d0xc,:ldddocxNMMMMMMM
MMMMWOclddddddddddl;:d00lcOKKKKKKKKx:cOKKKKKKKXKKxcdl:kXKKKKo'ld,.,oO0kddko;;lddddoll0WMMMMMMM
MMMMMXdcoddddddddddo:;:c,,dKKKKKKKO:;kKKKKXKKKKOocdkll0XKKXKo.',,c:,:dkkxc;codddddlcxNMMMMMMMM
MMMMMWKlcodddddddddddolcc,;xKKKKKXO;,xKKKKKKKK0d',kkcdKKKKKKd. 'cddl;,;;;:lddddddocdXWMMMMMMMM
MMMMMMW0lcoddddddddddddddl;;oOKKKK0l.,xKKKKKKKXk;'dxco0KKKKKx'.cddddoollooddddddocdKWMMMMMMMMM
MMMMMMMW0ocoddddddddddddddoc;:clllc;..'l0KKKKKK0xdO0olOXKKKKd,;odddddddddddddddocoKWMMMMMMMMMM
MMMMMMMMWKocldddddddddddddddolccccllol;.;xKKKKKKK0OKOk0XKKKOc,ldddddddddddddddlcdXWMMMMMMMMMMM
MMMMMMMMMWXxclodddddddddddddddddddddodoc'':oddddl:,:x0KKKKkc;codddddddddddddolckXWMMMMMMMMMMMM
MMMMMMMMMMMN0oclodddddddddddddddddddddddo:;,,,,;:c;'';cll:,;lodddddddddddddoco0NMMMMMMMMMMMMMM
MMMMMMMMMMMMWNklclodddddddddddddddddddddddddodddddool:;;:clodddoddddddddolclkXWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWXkolloddddddddddddddddddddddddddddddddddddddddddddddddddlcokXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWXOollodddddddddddddddddddddddddddddddddddddddddddddolloOXWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWN0xolloodddddddddddddddddddddddddddddddddddddoollox0NWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWN0xolllooddddddddddddddddddddddddddddooolclox0NWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWNKOxdolllloooodddddddddddddoooollllodxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOkxddoolllllllllllllooddxkOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWWNNWWWWMMMMMMMMMMMWWWNXKK0000000000KXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""", """MMMMMMMMMMWNKXWKk0NXKKkdxXMMWXKNWNXXK00OOOOOOOOO0KXXNNXXWMMMMMMMWKkONMMMMMMWXxoONMWNkclKM
MMMMMMMMMMWKdldo:look0l,oKNX0xollc:::;;;;;;;;;;;;;::cclx0XNWMMMW0ll0WMWMMMW0oo0WMMMWW0xKM
MMMMMMMMMMMWOc;;;;:xXNd:ldl:;,,;;:::::::::::::::::::;;;;::ldkXNOcoKWMMMMMNkldXWMMMMMW0xKM
MMMWWMMMMMMMXx:;;:xK0xc,,,'..',:cccccccccccccccccccccc:c::;;;:c:oKMMMMMWKdlkNMMMMMMNkcoXM
WMN00NMMMMMMW0l;;ldl;,,;::'.:o:',:cccccccccccccccccccccccccc:;,,:x0NWMNOloKWMMMMMW0ocxXMM
kKKo;dXWMMMMMXd;,,,,;::ccc,.oK0l',:ccccccccccccccccccccccccccc::;;;lkOdlxXMMMMMMXxcoKWMMM
lcc,..l0WWMMWKl,';::cccc:c;.:OK0o,;:cc::ccc:cccccccccccccccccccc:::;;,,lKWMMMMWOlckNMMMMM
d;.....;kXWXx:,;::cccccccc;.;OKK0c';ccccc::cccccccccccccccccccccc:cc::,,ckXWWXxcdKWMMMMMM
oc:;,'..'coc,,::cccccccccc;.,kKKKo..',,;;::cccccccccccccccccccccccc:cc:;,,lOkllONMMMMWNNM
WWNXK0kd:'',;:c:cccccccccc;.;OXKOl,;,......',::::cccccccc:cccccccccccccc:;,,;oKWMMMMNkdKM
MMMMMMW0c,;:c::ccccccccccc;.;OX0olxdcldxdol:,'''',;::::ccccccccccccccccccc:,,lKWMMWKdcxNM
MMMMMWO:,;:ccccccccccccccc;.;OKxlxdlxKKKXXKK0kxdc;,'';:cccccccccccccccccccc:,,lKWNOclOWMW
MMMMWO:,;:cccccccccccccccc;'l00oodlxKKKKKKKKKKKKK00o..:ccccccccccccccccccc:c:,,oOdcdXWMNO
MMMW0c,;:cc:cccccccccccccc;.:0kcolo0KKK0O0KKKKKKKKKk,.;ccccc:ccccccccccccc:cc:,',cONMW0o:
MMMXo,;:cccccccccccccccccc;.:OxlllOKKKKOocooox0KKKKk'.;ccccccccccccccccccccccc:,,dNWKd:cO
MMWk;,:ccccccccccccccccccc;'lxlood0KKKKKO;.';oKKKKKx..,ccccccccccc::;;,,,,,:ccc;,:kxc:xXW
MMXl';cccccccccccccccccccc;,llcldOKKKKKKO, ,ccd0KKXx..;ccc::;;;;;;;;:codo;.':cc:,',:dKWMM
MWO:,:cccccccccccccccccccc,':lclkKKKKKKKd'..',',:ldc..;;;;:cclodkOO00KKK0c.,:ccc:',xNMMMN
MNx,,:ccccccccccccccccccc:,.lkdx0XKXKKK0l..'....',;:codxkO0KKKKXXKK00Oxl;,;:cccc:,;OWMWKd
MNo';ccccccccccccccccccc:;'cOKKKKKKOdooolcldxxkO0KKKKKXKKKKKK0Oxoc:;::;,;:cccccc:,,xNNklo
MNl';cccccccccccccccccc:;'cOKKKK0OxdxO0KKKKKKKKKKKKKKKKK0Oxoc;,''',;::cccc:ccccc:,,oOdlkN
MNo';ccccccccccccccccc:,,l0KKKK0xxOKKKKKKKKKKKKKKXK0Oxoc;,,,,;::cccccccccccccccc:;';cdKWM
MNo,;:cccccccccccccc:;',d0KKKKK00KKKKKKKKKKKKKKKkoc:,,,,;::ccccccccccccccccccccc:,':ONMMM
MWx;,:ccccccccccccc:'.,xKKKKKKKKKKKKKKKKKKKKKKkc..';::cccccccccccccccccccccccccc:,;kWMMMM
MWO:,:ccccccccccc:;..ckKKKKKKKKKKKKKKKKKKKKOd:'..;cccccccccccccccccccccccccccccc;,c0MMMMM
MMXl';:ccccccccc:;..l0KKKKKKKKKKKKKKKKKKKKKx;..,::cc:cccccccccccccccccccccccc:c:,':kKKXNW
MMNk;,:c::;,'';:,'ckKKKKKKKKKKKKKKKKKKKKKKKk;.':cccc:ccccccccccccccccccccccccc:;,;collllo
MMMXl',;,';:,'..,o0KKKKKKKKKKKKKKKKKKKKKKKKo..,ccc:c::::cc:::cccccccc:cccccccc:,,dXWNXK0O
MMMW0:';cdkxc''ckKKKKKKKKKKKKKKKKKKKKKKXKKKk:..'''',,;::;;,,,,,;:cccccccccccc:;,lXMWMMMMM
MMMMWk;;dO0Oo,l0XKKKKKKKKKKKKKKKKKKKKKKKKKKK0xoodddxkOOOOkkxdol:;,,:cccccccc:;,c0WMMMMMMM
MMMMMNk::dO0kcc0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKKKKKKKKKKXKK0ko;';::cc:c:,,l0WMMMMMMMM
MMMMMMWOc;oO0d:d0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKx,.:cc:::,,lKWMMMMMMMMM
MMMMMMMW0l;cxOockKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000KKKO:.;cc:;,;xXWMMMMMMMMMM
MMMMMMMMWXx::okooOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOxolc:;;;;;;;::c:,,:::,,cONMMMMMMMMMMMM
MMMMMMMMMMWKo::lco0KKKKKKKKKKKKKKKKKKKKKKKKKKKOxl:,'',,,,;;;;;;;;;;:::;,:xXWMMMMMMMMMMMMM
MMMMMMMMMMMMN0o:,,o0K0OOkkkkxddooooodxxkkkkxoc,'',;:ccccccccccccc:::,,:dKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWKx:,::,..'',,,,,,,,,,;;;,,,,,,,;:ccccccccccccccc::;,,cxKWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWXkl;...;::ccccccccccccc:ccccccccccccccccccc::;,,:d0NWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWKko:;,;;::ccccccccccccccccccccccccc::;;,,;cdOXWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWXOxl:;;;;;;:::::cccccccc::::;;;;,;:cok0NWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWX0Oxolllcccccccccccccccclloxk0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"""
]
    return signs[index]
